### ISSUE TITLE
Mancanza meta open graph

### ISSUE THREAD

**Issue by giorrrgio** [italia/developers.italia.it#10]
Mancano i metatags og nell'head, andrebbero inseriti per migliorare la diffusione del sito sui social

**Comment by garak** [comment]
:+1:

**Comment by toretto460** [comment]
👍🏻

**Comment by rasky** [comment]
Io sono preso in conferenza per 2 giorni, se qualcuno mi fa una PR mergio subito grazie /cc @sbronzolo @umbros @IceOnFire

**Comment by IceOnFire** [comment]
Ci penso io

**Comment by IceOnFire** [comment]
Ho appena pushato, @rasky puoi verificare rapidamente se ti torna tutto?

**Comment by IceOnFire** [comment]
Se è sintatticamente corretto possiamo personalizzarlo per ogni pagina

**Comment by IceOnFire** [comment]
L'aggiunta di Jekyll SEO ha reso superfluo specificare esplicitamente i metatag.
