### ISSUE TITLE
"by relevance" ordering criteria

### ISSUE THREAD

**Issue by andreapoli** [italia/developers.italia.it#1022]
**Problem**
The "Developers Italia" open source software catalogue (https://developers.italia.it/it/search?type=software_open) uses a "by relevance" default ordering criteria. Looking at source code, the ordering seems unrelated to any real relevance criteria.

**Solution**
It should be clarified what metrics are used to identify the project relevance.

**Comment by bfabio** [comment]
"By relevance" makes sense when the user searches for something (which is the reason for the name: relevance to the terms searched), but is indeed misleading when the search field is empty.

I agree we should fallback to a secondary ordering when there are no search terms or find another name.
