### ISSUE TITLE
Filter on to-do page is broken

### ISSUE THREAD

**Issue by kerlon5** [italia/developers.italia.it#1083]
1. go to [to-do page](https://developers.italia.it/en/to-do)
2. filter the list by 'Projects' for example 'Web sites'
3. error: no matching records were found, but they exist

additional question: filter by projects contains 'Italia Design System' twice, one for 'bootstrap-' prefix projects and one for 'design-'. what is expected behavior here? should they be one group or do we need to distinguish them?

**Comment by mendaomn** [comment]
> @mendaomn hello, #1084 will resolve this issue you can add `--no-check-certificate` to wget options. this helped me for the first time build.

Thank you!
