### ISSUE TITLE
Pagina "Chi siamo"

### ISSUE THREAD

**Issue by vito80ba** [italia/developers.italia.it#109]
- [x] Verificare se opportuno lasciare Carlo C. come "mantainer"
- [x] Ercolani: modfiicare/cambiare foto

**Comment by ruphy** [comment]
Carlo non lavora più nel Team, quindi lo sposterei nella sezione "hanno contribuito".
Per il resto, eliminerei la dicitura "maintainer" che ha preso un'accezione particolare negli sviluppi di Developers Italia. Inoltre bisogna trovare un modo più compatto di parlare di project leader, perché sono tantissimi (tutti quelli dei vari progetti, una 30ina di persone?)

**Comment by alexrj** [comment]
Possiamo generare automaticamente la lista dei project leader e magari anche di tutte le persone della org Italia? Dobbiamo far vedere che nella community siamo in tanti e non siamo solo noi :-)

**Comment by vito80ba** [comment]
Propongo di fare fix come da consiglio di @ruphy e poi aprire nuova issue per quello suggerito da @alexrj

**Comment by alexrj** [comment]
...prosegue in #114
