### ISSUE TITLE
Alert al caricamento della pagina "Cosa fare"

### ISSUE THREAD

**Issue by jackcoral89** [italia/developers.italia.it#110]
<img width="1369" alt="screen shot 2018-03-03 at 6 34 22 pm" src="https://user-images.githubusercontent.com/27479143/36937302-9166319e-1f11-11e8-9ffb-5827a24eb6dc.png">

<img width="277" alt="screen shot 2018-03-03 at 6 49 13 pm" src="https://user-images.githubusercontent.com/27479143/36937446-a0ff8b26-1f13-11e8-8504-c46ec18f395f.png">

**Comment by ruphy** [comment]
Grazie @jackcoral89 !
guardo subito. credo sia un problema di CI

**Comment by ruphy** [comment]
Fixed! Thanks a lot!

**Comment by jackcoral89** [comment]
Ottimo, qual'era il problema ?

**Comment by ruphy** [comment]
@jackcoral89 mancava una copia della cartella github nei file compilati, cosa di cui ovviamente con jekyll in locale non ci si accorgeva. Una pulizia dei file remoti ha fatto saltare fuori il problema. Regressione probabilmente introdotta mesi fa...

**Comment by ruphy** [comment]
fixing commit: https://github.com/italia/developers.italia.it/commit/d68c48782f6e96430e4324856ac79ccc2670fa28
