### ISSUE TITLE
Translate /en/legal-notice into English

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#1124]
https://developers.italia.it/en/legal-notice is in Italian. We should translate it into English.

**Comment by Krish-bhardwaj** [comment]
Hi i am fresher and i would  like to contribute to your open source project

**Comment by bfabio** [comment]
Hello @Krish-bhardwaj, it's good to hear that. You can take a look at [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)

**Comment by goverdhan07** [comment]
hey @bfabio I have raised a PR for this issue. Can you please review it. Thanks!
