### ISSUE TITLE
Visual issues in the API page - swagger-ui

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#1138]
**Describe the bug**

As mentioned in https://twitter.com/aborruso/status/1488619461414371328 (thanks @aborruso), there is a visual glitch when browsing the API page through a mobile device. 
In particular, it looks like the issue lies in the `swagger-ui` component. 
This issue has already been raised (for example here https://github.com/italia/developers.italia.it/issues/498) but it's still present.

**To Reproduce**
1. Go to https://developers.italia.it/it/api/ispra-idrogeo with a mobile device or shrink the browser width to < 500px
3. Scroll down to the swagger section
4. See issue

**Expected behavior**

The swagger-ui section should be readable also on mobile devices without issues. As such, the `opblock-summary-path` and the `opblock-summary-description` should keep a decent size proportion. 

**Screenshots**

![Schermata da 2022-02-02 10-41-25](https://user-images.githubusercontent.com/93916407/152129673-3c962c22-2aaa-49d5-b68f-ba8605c87b30.png)

**Comment by aborruso** [comment]
Thank you very much @libremente

**Comment by bfabio** [comment]
There's an open issue upstream in swagger-ui: https://github.com/swagger-api/swagger-ui/issues/6647
