### ISSUE TITLE
Riformulare pagina Chi Siamo

### ISSUE THREAD

**Issue by vito80ba** [italia/developers.italia.it#114]
Riformulare pagina Chi siamo per dare risalto a tutte le persone coinvolte sui vari progetti: maintainers, project leader, contributori...

1. Elaborare proposta grafica
2. Verificare capacità di ottenere dati dai progetti github

**Comment by alexrj** [comment]
Io mi immagino una struttura del genere: per ogni progetto (CIE, SPID ecc.) elenchiamo i project leader (li abbiamo già in Jekyll perché li visualizziamo nelle pagine dei progetti) e poi i maintainer, che nel gergo di GitHub sarebbero i [collaborators](https://developer.github.com/v3/repos/collaborators/).

Poi sotto, indipendentemente dai progetti, mostrerei tutte [le persone appartenenti alla org _italia_](https://developer.github.com/v3/orgs/members/#members-list) il titolo "La community".

Cosa ne pensate @ruphy @rasky @sbronzolo?

**Comment by ruphy** [comment]
Ottima idea, anche quella di mostrare la community. Lascio a @italia/design ulteriori idee sulla realizzazione.

**Comment by alranel** [comment]
Done!
