### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#1196]
When searching, the results are often duplicated, eg: "comuni"

![image](https://user-images.githubusercontent.com/788293/167805639-b64f25c4-acb4-49f2-8de9-265d22ef6bf9.png)

cc @mfortini

**Comment by bfabio** [comment]
It should be fixed now, there was duplicate index (`publiccodes`) in the ElasticSearch `jekyll` alias, because the crawler automatically recreates it every night (the alias, not the index). The index name needs to be `publiccodes` (and not fe, `publiccodes_1` if we create a new one when reindexing for changes) and we can't use a different one as long as the crawler behaves like that.

@mfortini can you confirm?

**Comment by mfortini** [comment]
@bfabio I confirm it is fixed now. Thank you

**Comment by bfabio** [comment]
@mfortini thank you for reporting it!
