### ISSUE TITLE
Jekyll index in Elasticsearch is out of date

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#1197]
The Jekyll index in Elasticsearch is out of date:

```
$ curl -u $ELASTIC_USERNAME:$ELASTIC_PASSWORD http://localhost:9200/_cat/aliases
jekyll    jekyll-20220413112043
[...]
```

It should be updated at build but it stopped on 04/13, which is also the day [we switched to GitHub actions](https://github.com/italia/developers.italia.it/pull/1178) for building the site and that's certainly not a coincidence.

I'm guessing there's something wrong with the authentication to ElasticSearch (maybe wrong environment variables in the secrets?)

**Comment by sebbalex** [comment]
@bfabio Agree with you, not a coincidence. That makes me think about this dualism that always leads us to problems. Page building phase and search should be based on same data, same source.

**Comment by bfabio** [comment]
100% agree. The wonky build system we have will is causing more pain than it should

**Comment by bfabio** [comment]
Looks like we need `ELASTICSEARCH_URL` set

https://github.com/italia/developers.italia.it/runs/6382644010?check_suite_focus=true#step:7:54
