### ISSUE TITLE
When clicking on "More tags" in home page the viewport scrolls up

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#1204]
https://user-images.githubusercontent.com/788293/167885289-ba3cdb0f-f03b-41fe-bfa1-f65b8c69f4cd.mp4

**Comment by elenaAbbate** [comment]
Il bottone ha l'href collegato alla home page #?

**Comment by bfabio** [comment]
@elenaAbbate dovrebbe essere quello il problema, vuoi provare a correggerlo? :clap:

**Comment by elenaAbbate** [comment]
Ciao Fabio, certo! È la prima volta che entrò in dev Italia appena capisco come si usa il tutto volentieri 😂
