### ISSUE TITLE
Show more than 3 categories in software pages

### ISSUE THREAD

**Issue by evilaliv3** [italia/developers.italia.it#1230]
Hello,

i would like to report a possible bug in the developers.italia.it product page generation or an internal cache processing in relation to the recent addition of the software category [Whistleblowing](https://developers.italia.it/it/search?categories=whistleblowing)

While the software, that is listed in this catecotry, correctly shows up in the software search by category, it seems that the product page generation is failing to add the tag Whistleblowing on the product page.

**Comment by bfabio** [comment]
That's bizarre: looks like it has always shown [at most 3 categories for a long time](https://github.com/italia/developers.italia.it/blame/master/_layouts/software-details.html#L54)

On top of that, I'm not really sure where `page.popularCategories` comes from :thinking:

**Comment by evilaliv3** [comment]
Thank you for checking on this @bfabio 

From our point of view putting this limit is fair, and safe.

Actually for our project as it exists now a specific software category for whistleblowing we will proceed just listing that one alone.

**Comment by bfabio** [comment]
@evilaliv3 thanks

I think we should show more of them by default, and operate under the assumption then the order of appearance in the publiccode.yml is also a way to express what category fits the most.

Also, we should have a way to show all of them with a button or something, otherwise we are just removing information.

**Comment by bfabio** [comment]
So, what's happening here is:

the crawler is exporting "`popularCategories`" for each software ([code](https://github.com/italia/developers-italia-backend/blob/5d1f0ef1ab91c0c557752c676c8428c77fed876a/crawler/jekyll/softwares.go#L203)).

What are "`popularCategories`" of a software? Looks like they are [5 categories](https://github.com/italia/developers-italia-backend/blob/5d1f0ef1ab91c0c557752c676c8428c77fed876a/crawler/jekyll/main.go#L46) among the ones listed in `publiccode.yml`, ordered by the frequency they appear in other software in the catalog.  Then, as I mentioned above, the UI [cuts them to 3](https://github.com/italia/developers.italia.it/blame/master/_layouts/software-details.html#L54)

Pretty surprising and another example of why [the crawler shouldn't create YAML files](https://github.com/italia/developers-italia-backend/issues/243).

I kinda understand the reason behind it: to show the most relevant tags, but here "relevance" should be defined as "the categories better describing the **SHOWN** software".

That code needs to go.
