### ISSUE TITLE
double indexing

### ISSUE THREAD

**Issue by lorello** [italia/developers.italia.it#1266]
Hi!
Our software has two pages on developers.italia.it:

* https://developers.italia.it/it/software/opencontent-stanzadelcittadino-cf016d
* https://developers.italia.it/it/software/opencontent-stanza-del-cittadino-core-410a6e

The first one is a dead page (last release 1.10.0), the second one is updated (last release 1.23.3).
Can you remove the dead page from your index?

Funny detail: the vitality of the dead page is greater than that of the living page :-)

dead page vitality:
![image](https://user-images.githubusercontent.com/694058/176932201-150652b5-8baa-4d3e-8ab1-79c4c51efc95.png)

live page vitality:
![image](https://user-images.githubusercontent.com/694058/176932588-80ddb446-8438-4921-9edb-b8248280d3bc.png)

Thanks!

**Comment by bfabio** [comment]
Removed :+1:
