### ISSUE TITLE
container: "Invalid Elasticsearch configuration provided, skipping indexing..." after page change

### ISSUE THREAD

**Issue by zukka77** [italia/developers.italia.it#1301]
**Describe the bug**
When previewing the site using the container after a page change and file regeneration i get:
```
Invalid Elasticsearch configuration provided, skipping indexing...
  Elasticsearch url must start with 'http' or 'https'
    Current Value: ENV_ELASTICSEARCH_URL
    Current Source: CONFIG
                    ...done in 11.413746937 seconds.
```

**To Reproduce**

**Expected behavior**

Don't know if the functionality is there (I don't know how to try)

**Comment by libremente** [comment]
Hi @zukka77, did you `cp .env.example .env` by chance?
The env is there https://github.com/italia/developers.italia.it/blob/master/.env.example#L5 so it should eventually work

**Comment by zukka77** [comment]
nope I just "echoed" RUNAS in .env... 
Copying the file does the trick... I should have RTFM :sweat_smile:
