### ISSUE TITLE
The schema section in API specs is too narrow

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#1305]
The schema section of responses in the API specs rendering is too narrow, for example in https://developers.italia.it/it/api/covid19-umbria (Firefox 104, desktop)

![image](https://user-images.githubusercontent.com/788293/187406274-9defaa15-3a7c-4b03-beeb-c547207efa69.png)

or

![image](https://user-images.githubusercontent.com/788293/187405825-6933429d-0b17-45d2-95c5-923322bf2168.png)

**Comment by bfabio** [comment]
Maybe related to #1138

**Comment by libremente** [comment]
I guess @sebbalex started working on a fix some years ago

**Comment by sebbalex** [comment]
> I guess @sebbalex started working on a fix some years ago

Yes, we have applied a fix for what is in our domain but the main issue was in swagger-ui side
