### ISSUE TITLE
Topic Links Don't Work

### ISSUE THREAD

**Issue by PyGera** [italia/developers.italia.it#1343]
**Describe the bug**
When you click on some topic link in the bottom of a post. It gets to 404 page.

**To Reproduce**

1. go to developers.italia.it
2. click on News
3. click on a Post
4. click on a Topic

**Expected behavior**

I see the posts about that topic

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [MacBook Air 2020 M1]
 - OS: [macOS Ventura]
 - Browser [Safari]
 - Version [16.1]

**Additional context**
Add any other context about the problem here.-->

**Comment by bfabio** [comment]
Thanks @PyGera, confirming.

Looks like this happens in https://developers.italia.it/it/news/2022/12/21/Developers-Italia-approda-su-Mastodon which has the work casing in tags. Have you seen other instances of it besides that page?

**Comment by PyGera** [comment]
>Have you seen other instances of it besides that page?

I have noticed this only on that page

**Comment by bfabio** [comment]
@PyGera thanks, closing then :+1:
