### ISSUE TITLE
Bootstrap Italia Bundle Min JS 2.3.4 + Angular 13 | DOMException 

### ISSUE THREAD

**Issue by alessiobilleci** [italia/developers.italia.it#1360]
**Describe the bug**
Avendo gruppi di due radio button costruiti dinamicamente (hanno lo stesso name e id univoco) al click dei uno dei due viene mostrato il segunte errore in console:
**Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '#id' is not a valid selector.**
con riferimento a _node_modules\bootstrap-italia\dist\js\bootstrap-italia.bundle.min.js_

**Comment by bfabio** [comment]
Ciao @alessiobilleci, volevi forse aprire un'issue sul [repository di boostrap-italia](https://github.com/italia/bootstrap-italia)?

Ti consiglio anche lo Slack https://slack.developers.italia.it e il Forum https://forum.italia.it
