### ISSUE TITLE
Title "Developers Italia" changes to "Developper UK" when page is translated 

### ISSUE THREAD

**Issue by WhatAb0utThisName** [italia/developers.italia.it#1440]
**Describe the bug**
Title "Developers Italia" changes to "Developper UK" when page is translated in page 

**To Reproduce**
1. Go to https://developers.italia.it
2. Click on translate to english in Edge browser, desktop version
3. See error
-->

**Expected behavior**
Title should stay unchanged

**Screenshots**
![Capture d’écran 2024-01-03 093419](https://github.com/italia/developers.italia.it/assets/109308576/258b8db4-37da-452d-b63d-c64c853c80b1)

**Comment by bfabio** [comment]
@WhatAb0utThisName hi, this is due to whatever shenanigans Edge is using to translate the page, probably GPT-related 

Funny, but not a bug on our side :D
