### ISSUE TITLE
Home platforms section displays incorrect titles

### ISSUE THREAD

**Issue by smonolo** [italia/developers.italia.it#1454]
**Describe the bug**

Items belonging to the platforms section of the home page are displaying a wrong title. It is rendering the name of the file they are related to, but no the human-friendly formatted value.

This issue does not persist in the actual platforms page, where the correctly title is shown as supposed.

**To Reproduce**

1. Go to the home page (`/` or `/en`)
2. Scroll down to platforms ("Piattaforme")
3. Look at each item's title

**Expected behavior**

I should see each item display the correctly formatted title.

**Screenshots**

![image](https://github.com/italia/developers.italia.it/assets/29622224/37ab3a1d-df1c-4ea8-a8f0-da1ca494de38)

**Additional context**

It looks like the issue is caused by the home page cards trying to display `item.name` instead of `item.title`, leaving the correct value as a fallback. `platforms.html` correctly uses `platform.title` which seems to be working.

**Comment by bfabio** [comment]
Looks like this was introduced by #1446, maybe then new Jekyll version changed something
