### ISSUE TITLE
Aggiungere al Catalogo il software Opencity italia - ASL

### ISSUE THREAD

**Issue by federicataraboi** [italia/developers.italia.it#1522]
### Il software è rilevante per la Pubblica Amministrazione italiana

- [X] Confermo

### Il software NON è di titolarità di una Pubblica Amministrazione

- [X] Confermo

### Il repository contiene un file publiccode.yml valido

- [X] Confermo

### URL

https://gitlab.com/opencity-labs/sito-istituzionale/opencityitalia-asl/

### Ulteriori informazioni

Opencity Italia ASL è un modello di sito web avanzato per le Azienda Sanitarie italiane, che garantisce un’esperienza utente completamente basata su linee guida, prototipi, architettura dell’informazione previsti dal Dipartimento per la Trasformazione Digitale in collaborazione con AgID (Agenzia per l’Italia Digitale) nel 2024.

**Comment by tensor5** [comment]
https://developers.italia.it/it/software/79f9de10-b0ce-44c1-80c0-9bc6a55d49f6
