### ISSUE TITLE
Mailup riporta sporadicamente errori 500 in fase di registrazione alla newsletter

### ISSUE THREAD

**Issue by gvarisco** [italia/developers.italia.it#21]
Ci è stato segnalato che https://a0x0b4.mailupclient.com/frontend/subscribe.aspx risponde in alcune occasioni con errore 500. (nessun parametro particolare nella POST, normali indirizzi e-mail)

TODO:

- Follow-up con supporto tecnico Mailup e apertura ticket.

**Comment by rasky** [comment]
Vedi anche: https://twitter.com/mrzippetto/status/845671570446172162

**Comment by alranel** [comment]
Il problema non si è più presentato, chiudo
