### ISSUE TITLE
cookiebar - Link "Privacy policy" non definito

### ISSUE THREAD

**Issue by gvarisco** [italia/developers.italia.it#24]
Il link "Privacy policy" presente nella cookiebar risulta riportare erroneamente a https://developers.italia.it. 

TODO:
- [ ]  Dichiarare "privacy_link" in _config.yml
- [ ] Gestire supporto multilingua per privacy policy link
- [ ] Verificare presenza privacy policy EN
 
ref. https://github.com/italia/developers.italia.it/blob/master/_includes/cookiebar.html

**Comment by alranel** [comment]
Risolta tempo fa, chiudo
