### ISSUE TITLE
API pages are not indexed

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#256]
Searchyll does not index pages generated by `data_page_generator.rb`.

This repository contains a modified `data_page_generator.rb` ([upstream here](https://github.com/avillafiorita/jekyll-datapage_gen)) that allows to add default data values to generated pages (we need `lang` and `type`).

**Comment by alranel** [comment]
Actually, they seem to be indexed (but not re-indexed automatically when using `bundle exec jekyll serve`. Check this.

**Comment by libremente** [comment]
Right now it seems they are indexed twice (en and it) with the same title (in italian).

**Comment by sebbalex** [comment]
APIs pages were set by default to lang `it` even if they were published under another language folder, this caused duplicated entries in search engine when website is set to ITA lang and no results with ENG lang.
Search engine will filter results based on language set in website so they should be visibile in both languages even if they are published in only one of them.
