### ISSUE TITLE
Mail di conferma registrazione newsletter - Oggetto e contenuto anonimi

### ISSUE THREAD

**Issue by nsanitate** [italia/developers.italia.it#26]
Le mail di conferma registrazione newsletter si presentano così
![risposta](https://cloud.githubusercontent.com/assets/666044/24356448/54b46b2c-12fa-11e7-90d6-432a8106087c.png)
Non c'è nessun riferimento alla lista alla quale ci si sta iscrivendo, ne al dominio di riferimento.
Sarebbe necessario personalizzare oggetto e contenuto.

**Comment by alranel** [comment]
Chiudo questa (utile) segnalazione perché il problema è stato risolto al tempo :-)
