### ISSUE TITLE
Some pages are indexed twice

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#261]
The page `/it/come-partecipo` is indexed twice in Elasticsearch.

I suspect it may be seen by Searchyll both as a "document" and as a "post" (see searchyll.rb).

**Comment by libremente** [comment]
Still valid, check this @sebbalex

**Comment by sebbalex** [comment]
@alranel I can confirm your doubts, they are indexed twice, both for `documents` and `pages`

```
        indexing page /it/come-partecipo/
        indexing document /it/come-partecipo/
```
