### ISSUE TITLE
Otello img preview is slightly smaller than others

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#271]
Otello img preview is slightly smaller than others. As such, the line is broken. See screenshot:
![schermata da 2019-02-18 18-37-10](https://user-images.githubusercontent.com/25111463/52968041-57169500-33ac-11e9-8a2b-889780fd2984.png)

**Comment by libremente** [comment]
Still holds, inserting in 2.3.1 milestone.

**Comment by ffranchina** [comment]
Hello @libremente, I tried to reproduce this issue with no success (https://developers.italia.it/it/search?type=platforms&page=1&sort=relevance). Is it browser dependent or meanwhile has been solved by some other commit? Thanks :)

**Comment by libremente** [comment]
Hi @ffranchina, it that page it is OK, but not on this one: https://developers.italia.it/it/piattaforme/
