### ISSUE TITLE
Slack icon missing

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#272]
In `come-lo-uso`, the slack icon is missing in the button at the end of the page. See screenshot for reference:
![schermata da 2019-02-18 18-38-54](https://user-images.githubusercontent.com/25111463/52968104-8927f700-33ac-11e9-9a38-da448e16d523.png)

**Comment by alranel** [comment]
Fixed. The italia-icon-font has no Slack icon so I used a generic one:

![Screen Shot 2019-03-19 at 21 33 17](https://user-images.githubusercontent.com/594957/54639852-a5dc4b00-4a8e-11e9-9b76-f121f6d1399b.png)
