### ISSUE TITLE
Link color issue, accessibility problem

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#273]
In the `contacts` page, text is in black over the blue background, limiting its visibility.
See screenshot:
![schermata da 2019-02-18 18-40-15](https://user-images.githubusercontent.com/25111463/52968196-c1c7d080-33ac-11e9-9631-f8edc3605186.png)

**Comment by libremente** [comment]
Now (FF 66 - GNU/Linux OS):
![Schermata da 2019-04-17 19-01-12](https://user-images.githubusercontent.com/25111463/56306802-bb06d100-6143-11e9-95a6-5548522de26f.png)
with mouse over -> double underline

**Comment by alranel** [comment]
Fixed
