### ISSUE TITLE
Display software scopes

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#287]
As of now, the software catalog can be browsed by category, according to the `categories` key of publiccode.yml.
We should also display the `intendedAudience.scope` key of the publiccode.yml file, in the software details pages, in the search engine sidebar and in home page.

Note that since `intendedAudience.scope` is an optional key, we should probably hard-code an additional "other" item that allows to display those entries whose scope is not populated.

**Comment by alranel** [comment]
As of https://github.com/italia/developers-italia-backend/commit/906dbb0a389a29523b50c584bce492aad6cdbb4c, the backend crawler also exports a `software_scopes.yml` file with the distinct values mentioned in the catalog.

**Comment by libremente** [comment]
Substitute the "category" list (not the first one below the title but the second one after the features description).
