### ISSUE TITLE
titolo e dida box docs.developers

### ISSUE THREAD

**Issue by sbronzolo** [italia/developers.italia.it#3]
@umbros ciao so che tu lavori su  https://docs.developers.italia.it/

c'è un box "Altra documentazione" che dovrebbe cambiare titolo e diventare "Altri progetti"
Il testo "In arrivo" dovrebbe diventare "Idee per nuovi progetti dentro Italia Developers, vai al [forum](https://forum.developers.italia.it/t/nuovi-progetti-dentro-italia-developers/24)

grazie
cc @rasky

**Comment by alranel** [comment]
Obsoleta, chiudo
