### ISSUE TITLE
Screenshot previews in "interest related softwares" section are broken

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#301]
The size of the screenshots preview in the `interestRelatedSoftwares` section of a software page are not the same of the previews in the `/software` page.
As such, the resulting effect is shown:
![Schermata da 2019-04-08 16-09-44](https://user-images.githubusercontent.com/25111463/55730567-cad23700-5a18-11e9-8073-14e2d99cacf1.png)

which is unpleasant.
I'd suggest to uniform the size of the screenshot previews.

**Comment by sebbalex** [comment]
Actually as for spec we do have a suggested format for those images but in real use they are in different ratio. IMHO I'd suggest to avoid to have images at fixed size it may resulting in some graphic stretch.

One possible solution is crop, see below for preview:
![Screenshot 2019-04-24 at 12 46 38](https://user-images.githubusercontent.com/11008116/56654679-ef711480-6690-11e9-8198-475b2680d533.png)

@alranel @libremente what's your opinion?

**Comment by alranel** [comment]
I vote for cropping. That's what we already do in other pages IIRC.

**Comment by libremente** [comment]
Crop may be a good solution, however, the drawback is that some previews will be totally senseless (see the third one in your example). 
I think in this phase that's not a big deal, we can go for cropping and then we can arrange something cleaner

**Comment by sebbalex** [comment]
> Crop may be a good solution, however, the drawback is that some previews will be totally senseless (see the third one in your example).
> I think in this phase that's not a big deal, we can go for cropping and then we can arrange something cleaner in the future.

Sure, we can figure out for something cleaner later in future.

**Comment by sebbalex** [comment]
Closed by commit ebdf70c
