### ISSUE TITLE
Decisione sul package manager JS da utilizzare

### ISSUE THREAD

**Issue by francescozaia** [italia/developers.italia.it#303]
Al momento il README fa riferimento a `npm install` ma nel repo non c'è il `package-lock.json`, ma il lock per Yarn. contestualmente andrebbe aggiornato anche il file di configurazione per CircleCI.

**Comment by libremente** [comment]
Idee @francescozaia? Sicuramente yarn è più veloce, io voterei per quello.

**Comment by francescozaia** [comment]
E allora [`pnpm`](https://pnpm.js.org/)? 😄 
Per ora, visto che [non c'è un chiaro vincitore](https://iamturns.com/yarn-vs-npm-2018/) tra i due più usati e che all'interno del repo c'è anche un altro progetto che usa già `npm`, rimarrei su quello semplicemente consolidando lockfiles, readme, ecc.

**Comment by libremente** [comment]
Velocissimo! :rocket: 
Ok per mantenere npm per me

**Comment by alranel** [comment]
Questa si può chiudere @francescozaia, vero?
