### ISSUE TITLE
Graphical glitch on top link list

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#308]
I see the link list in this way:
![Schermata da 2019-04-16 22-14-13](https://user-images.githubusercontent.com/25111463/56241072-3a899700-6095-11e9-9d5a-7964d5759716.png)
with a floating white bar at the bottom.

**Comment by Pratyush1197** [comment]
Hello I want to work on this issue Can you please tell me how it is expected to behave? Thanku

**Comment by libremente** [comment]
HI @Pratyush1197 and thanks for the interest! Personally I don't like the fact that below the white bar there is still some blue space, it looks like it's floating. I'd like that white bar to be the last element in that div. What do you think @sebbalex?

**Comment by sebbalex** [comment]
@libremente this is exactly what we meant with this issue. 👍

**Comment by Pratyush1197** [comment]
Ok I will try to improve the design as you mentioned Thanku :)
