### ISSUE TITLE
SVG not loading correctly

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#310]
This SVG `it-telephone` is not loading properly.
See:
![Schermata da 2019-04-17 18-26-51](https://user-images.githubusercontent.com/25111463/56304499-83e1f100-613e-11e9-8a1c-92828874a0df.png)

@francescozaia said this is probably due to the fact that both the old and the new way of handling the fonts is used.

**Comment by francescozaia** [comment]
I'll have a look at it asap!

**Comment by alranel** [comment]
This is fixed now (thank you @francescozaia!):

![Screenshot 2019-05-07 at 16 16 13](https://user-images.githubusercontent.com/594957/57306626-75567c00-70e3-11e9-8780-25e227dcdbb1.png)
