### ISSUE TITLE
Improve screenshots in the software catalogue

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#319]
The Photoswipe bug (#267) was fixed but we should still improve how screenshots are rendered, by not showing them in full size but applying a `max-width` so that they are resized and no vertical scrollbar is displayed:

![Screen Shot 2019-04-29 at 12 53 00](https://user-images.githubusercontent.com/594957/56892829-15c3f500-6a81-11e9-9dd3-fdbac48f950c.png)

**Comment by alranel** [comment]
Also, some screenshots are stretched for no reason:
![Screen Shot 2019-04-30 at 10 16 32](https://user-images.githubusercontent.com/594957/56948639-0dc38e00-6b31-11e9-8f7c-7eb94801f466.png)
![Screen Shot 2019-04-30 at 10 16 14](https://user-images.githubusercontent.com/594957/56948640-0e5c2480-6b31-11e9-8e4f-c232121cda7d.png)

**Comment by libremente** [comment]
In FF 66 on GNU/Linux I see it in this way:
![Schermata da 2019-05-07 16-56-33](https://user-images.githubusercontent.com/25111463/57309919-31667580-70e9-11e9-9be5-fd74a10d6423.png)

**Comment by sebbalex** [comment]
Closed by commit 92ba08b

**Comment by sebbalex** [comment]
Reopened: Safari is still affected by this issue

![Screenshot 2019-05-14 at 15 02 21](https://user-images.githubusercontent.com/11008116/57700022-63338b00-7659-11e9-81f8-a1e86b28a920.png)
