### ISSUE TITLE
Display a placeholder when external images are not found

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#326]
We load software screenshots directly from their code hosting websites, such as GitHub raw. Such URLs may get broken when something is changed in the original repository. Our crawler automatically checks image existence at each run, so the data used for rendering the catalogue is always clean and does not reference non-existing images; however, there might be a lag between the upstream change, the next run of the crawler and the website rebuild.

![Screenshot 2019-05-14 at 12 39 07](https://user-images.githubusercontent.com/594957/57691746-4beaa280-7645-11e9-85bc-e0c0ca07637f.png)

We should add some Javascript code (`onerror`?) that handles broken images gracefully. Screenshots used in listings should be replaced with the generic placeholder, while screenshots in the software details pages should be just removed.

**Comment by sebbalex** [comment]
Closed by commit 511bba1
