### ISSUE TITLE
Disable link to maintainer when the value is undefined

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#330]
Right now, the `contract` field inside a software card is always populated as a link.
However, since the `website` key of the contractors is *not* mandatory, there should be some logic to check this. 
My guess is that the `contractors.website` in the template context will be undefined / empty. 
See this image to know the exact location of the issue:
![Schermata da 2019-05-21 10-28-33](https://user-images.githubusercontent.com/25111463/58080493-9e7f0e00-7bb3-11e9-8d9a-14d5f546d16d.png)
The `Almaviva` link is empty. 
Furthermore, it could be nice to follow what the mockup suggests: since this is an external link, it's better to notify the user with some sort of icon placed next to the link. I'd suggest this BSI icon: it-external-link (https://italia.github.io/bootstrap-italia/docs/utilities/icone/)

**Comment by ffranchina** [comment]
Hello @libremente, could you please post an example URL where the problem occurs? Thanks in advance!

**Comment by libremente** [comment]
Hi @ffranchina, this should be a good case: https://developers.italia.it/it/software/m_bac-istitutocentralecatalogounicobiblio-sbnweb-open

I believe it's just a matter of inserting a very simple if-then-else logic in the md file
