### ISSUE TITLE
Restructure the software page

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#331]
The software section has two subsections, one for reuse sw and one for FOSS. I believe we should insert some sort of pagination for both subsections since, if not, the `FOSS` subsection will be pushed in the very bottom of the page and won't be visible. 
Maybe the jekyll pagination plugin could help.

**Comment by alranel** [comment]
As discussed, the /it/software and /en/software pages should be changed like this:

* Intro text
* The catalog of Developers Italia contains *n* entries published by Public Entities and *n* published by third-party developers.
* Two big buttons (find better/shorter labels):
   * [Click here to browse software published by Public Entities](https://developers.italia.it/it/search?type=reuse_software)
   * [Click here to browse software published by third-parties](https://developers.italia.it/it/search?type=software_open)
* The most 4 recent entries (merging reuse and third party)
* The most 4 active entries (merging reuse and third party)

**Comment by alranel** [comment]
As discussed today, the two big buttons should be replaced by the larger white/blue template we use in several pages including /it/riuso. Let's try with no image first.

Let's have a "View all" button below each section, linked to the search results with no filter but ordered according to the criteria used for the section.

This page should also include one more block with the gallery of publishers (PAs) which published most packages in the catalog. The "View all" button should link to /it/pa.

**Comment by libremente** [comment]
Fixed by #407, closing! 🎉
