### ISSUE TITLE
Generate pages for individual public entities

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#334]
Goal: provide each public entity with their own page on Developers Italia where their software is automatically listed.

* URL: /it/pa/<ipa> (ad es. /it/pa/m_it)
* L’interfaccia sarà quella del motore di ricerca con le seguenti variazioni:
   * prima dei risultati mostriamo un secondo header con il nome dell’ente e l’URL del sito web (e una breve introduzione del tipo “questa pagina contiene il software bla bla”?)
   * non mostriamo la stringa “Risultati di ricerca:”
   * nascondiamo il filtro per tipologia
* I risultati sono ottenuti filtrando per:
   * publiccode.it.riuso.codiceIPA (pagine relative ad un ente)

Modifiche alle schede dei software:
* aggiungere il link dal publisher alla sua pagina statica nel sito.

Modifiche all’onboarding:
* chiedere URL sito web istituzionale (opzionale), precompilato con quello eventualmente fornito da IndicePA
* aggiungere sito_istituzionale nell’indice di IndicePA in Elasticsearch

**Comment by alranel** [comment]
Top-right text:

> Questa pagina elenca il software di cui l'ente è titolare e che è stato pubblicato con licenza aperta ai sensi dell'art. 69 del Codice dell'Amministrazione Digitale.

> This page lists the software solutions owned by this public entity and released under an open license according to art. 69 of the Digital Administration Code.

**Comment by sebbalex** [comment]
Closing by 2387409
