### ISSUE TITLE
Restore the "cosa fare" page

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#337]
The previous website had a "Cosa fare" page which listed all the issues in github.com/italia having the "help wanted" label (see #65 ). This page was not included in the first release of the new website.

We should restore this page. If the client-side rendering with the search engine is too complicated to restore, we should at least do a basic Jekyll server-side rendering with no pagination.

See also #75.

**Comment by sebbalex** [comment]
It is important to understand where we should link the page. Also consider to create a snippet as a simple jekyll include layout file.
Possible pages where we could reach this page are: `Platforms`, `How to`

**Comment by libremente** [comment]
https://github.com/italia/developers.italia.it/pull/357 reintroduces the page. However, we still don't have a link to it.

**Comment by sebbalex** [comment]
As discussed we should place the link inside `Platform` page below the right subtitle and in `Get Involved` page in `Platform` section as a simple button with `Contribute` label.

**Comment by sebbalex** [comment]
Closed by commit 6f9ad7c
