### ISSUE TITLE
Variants are not correctly displayed

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#341]
https://developers.italia.it/it/software/pcm-teamdigitale-pdnd-open-notebooks
is based on
https://developers.italia.it/it/software/pcm-teamdigitale-daf-nteract
which is based on
https://github.com/nteract/nteract

The page for pdnd-open-notebooks should display:

* the name of the publisher of daf-nteract
* the vitality index of daf-nteract
* the diff of features between daf-nteract and pdnd-open-notebooks

The page for daf-nteract should not display any information about the parent project (nteract/nteract) because it's not in the catalog.

**Comment by alranel** [comment]
Maybe I can also move `oldFeatures` within `oldVariants`.

**Comment by alranel** [comment]
The name of the publisher is located in `variant.publiccode.legal.repoOwner`.

I think that `vitalityScore` can be fetched directly in Jekyll by doing something like this:

```
{% assign variant_sw = site.data.crawler.softwares | where: "id", variant.id %}
{{ variant_sw.vitalityScore }}
```

The diff of features computed between the current software and *all* the variants is located in `oldFeatures` (this is why the diff is not under the single variants).

I think no change is needed on the the YAML files and that everything can be fixed on the Jekyll side. Let me know if this is not the case!

**Comment by sebbalex** [comment]
As for this statement:

> The page for daf-nteract should not display any information about the parent project (nteract/nteract) because it's not in the catalog.

This is correct, then in yaml I won't expect a variant for `daf-nteract`, it should be available only for `pdnd-open-notebooks` correct?
@alranel

**Comment by sebbalex** [comment]
> This is correct, then in yaml I won't expect a variant for daf-nteract, it should be available only for pdnd-open-notebooks correct?

Yes this is correct, variants are only for related software in catalog.
