### ISSUE TITLE
4xx & 5xx error pages

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#346]
Error pages are now shown from web server, they must be served by developers.italia.it style.

**Comment by masihtak** [comment]
You need custom design for 4xx & 5xx error pages?

**Comment by sebbalex** [comment]
Design must be in line with website style and following best-practice and rules of main theme [Bootstrap Italia](https://italia.github.io/bootstrap-italia/)

**Comment by masihtak** [comment]
Ok, I will working on this as well

**Comment by sebbalex** [comment]
Thanks @masihtak for the work you have made so far.
