### ISSUE TITLE
Add visual feedback when crawler validation fails

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#365]
## Case study

- t0: A `publiccode.yml` file is correctly parsed by the crawler and the sw page is created in the catalog
- t1: A breaking change (bug) is inserted in the `publiccode.yml` file and erroneously pushed on master by the operator
- t2: The crawler fails the validation and, as such, the old page stays live - the new mods are not inserted.

Right now, at `t2` no feedback is sent to the creator who, in most of the cases, waits some days and then pings us to get more info. 

### Optimal solution proposed
A good solution would be to immediately send a feedback (through email?) to the committer (maybe using the github API like https://api.github.com/users/libremente/events/public to retry the last commiter email address?) so that it will be immediate to fix the issues and re-submit. 
However, I believe this implies way too much work at this stage and we can work around the bug with a simpler solution (see below).

### Suboptimal solution proposed
As discussed with @alranel @biancini, it might be way faster to insert a link in the footer of the sw page pointing to a URL built something like:
`https://publiccode-editor.developers.italia.it?path=https://github.com/<org>/<repo>/publiccode.yml&action=validate`
so that the responsible of the software can directly see the errors, fix them in the editor, export the new file and push it in the repo. The link should *kindly* say that the validation did not pass (I would suggest avoiding phrases like *ERROR*). 
Maybe in order to do this we could insert an indication of the last good parsing time and, in case that time is in the past, insert the link discussed above. 

Comments are warmly welcome. 
@sebbalex

**Comment by libremente** [comment]
This is strictly linked and dependent on https://github.com/italia/publiccode-editor/pull/125/files

@sebbalex could you please update on this? This is a super cool feature :rocket:

**Comment by sebbalex** [comment]
@libremente feature is now live! I keep this open since this point is not done yet:
>it might be way faster to insert a link in the footer of the sw page pointing to a URL built something like:
https://publiccode-editor.developers.italia.it?path=https://github.com/<org>/<repo>/publiccode.yml&action=validate

but I would track this with a dedicated issue.
