### ISSUE TITLE
 Include subtitle in software listing page

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#368]
I believe that the software listing page should also contain a subtitle.
Right now the title is not self explicative enough and it does not help the reader.

**Comment by libremente** [comment]
Probably also this one is superseded by https://github.com/italia/developers.italia.it/issues/331#issuecomment-521279653

**Comment by libremente** [comment]
I think #562 is tackling exactly this. This is a preview:
![Schermata da 2020-05-17 19-14-00](https://user-images.githubusercontent.com/25111463/82155066-99aa7400-9872-11ea-81bb-ad3dced2380a.png)

**Comment by sebbalex** [comment]
We have a live preview here: https://deploy-preview-562--developers-italia.netlify.app/it/search?type=reuse_software&page=0&sort=relevance
suggestions are welcome!

cc @libremente @bfabio

**Comment by bfabio** [comment]
@sebbalex Really nice! A couple things I noticed:

* We probably want the "Read more" part to be aligned to the bottom of the card
* What about showing the full description on hover? It could be useful for software whose description is truncated
* Can we align the header when "Software open source" is next to another type?
![Screenshot_2020-09-10 Catalogo](https://user-images.githubusercontent.com/788293/92754282-f9c9a680-f38a-11ea-9d6b-89213bb32600.png)
Maybe renaming "Software open source" to just "Open source"?

**Comment by sebbalex** [comment]
> @sebbalex Really nice! A couple things I noticed:
> 
> * We probably want the "Read more" part to be aligned to the bottom of the card
definitely, it would benefit the readability.

> * What about showing the full description on hover? It could be useful for software whose description is truncated
👍 
> * Can we align the header when "Software open source" is next to another type?
>   Maybe renaming "Software open source" to just "Open source"?
@libremente WDYT?

**Comment by libremente** [comment]
>     * We probably want the "Read more" part to be aligned to the bottom of the card
Ok

>     * What about showing the full description on hover? It could be useful for software whose description is truncated

I am not 100% convinced about this. I mean, it could be nice but we should probably open a dedicated issue and work on it later on with lower priority. 

>     * Can we align the header when "Software open source" is next to another type?
>       Maybe renaming "Software open source" to just "Open source"?
Let's try to shrink the font size to 0.75rem and see what happens.

**Comment by sebbalex** [comment]
@libremente @bfabio thanks for your suggestions, I think I have addressed all of them, please have a look:
https://deploy-preview-562--developers-italia.netlify.app/it/search?type=software_open&page=0&sort=relevance

**Comment by bfabio** [comment]
@sebbalex Great, I think that's ready to be checked in :rocket:

**Comment by libremente** [comment]
I need to review it later, I'm not so convinced @sebbalex

**Comment by libremente** [comment]
@sebbalex personally I believe that the space above "Leggi tutto" is too much and there is no clear separation among the rows.
![Schermata da 2020-09-11 15-25-01](https://user-images.githubusercontent.com/25111463/92930966-11fcfc80-f443-11ea-9afe-cde60b82c0a5.png)
I'd try to reduce that space a little, something like `bottom: 40px`. WDYT?

**Comment by sebbalex** [comment]
Cards are auto-adapted to single card which has the highest height so we could tune that param as we wish, going to set it to 40px.
