### ISSUE TITLE
Check how software is ordered in the catalog

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#369]
– Search results: it should be ordered by relevance and descending vitality
– Software page: it should be ordered randomly
– Home page: it should be ordered randomly
– Public entity page: it should be ordered alphabetically

**Comment by libremente** [comment]
I don't get the second point, in the software page (https://developers.italia.it/it/software/) there is no way to display the results randomly. I think I'll just leave it in the following way: 
- Search results: it should be ordered by relevance and descending vitality
- Software page: follow the pre-defined orders: most recent, most active, virtuous PAs. 
- Home page: it should be ordered randomly
- Public entity page: it should be ordered alphabetically

**Comment by libremente** [comment]
As discussed with @bfabio we are now leaving the default search results to relevance. We will fix the vitality in the next version of the search engine.
