### ISSUE TITLE
Creare una pagina di lista degli "strumenti"

### ISSUE THREAD

**Issue by sbronzolo** [italia/developers.italia.it#37]
In pratica una pagina con questo template https://developers.italia.it/it/progetti/ ma che descriva gli strumenti (github, docs, forum, api) così come sono descritti in home page

La descrizione degli strumenti, testi compresi, è già stata fatta in home page

**Comment by alranel** [comment]
Ad oggi abbiamo creato https://developers.italia.it/it/come-partecipo, chiudo
