### ISSUE TITLE
Bug: incomplete title if no search query is entered

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#370]
If no search term is entered, this incomplete title is displayed:

![Screenshot 2019-08-14 at 16 51 50](https://user-images.githubusercontent.com/594957/63031146-d85e6880-beb3-11e9-970b-05420e4988ef.png)

We should actually replace that title with an editable text input that allows the user to change the search term interactively.

**Comment by sakshi1499** [comment]
If you add the searched word to be displayed directly on the screen, It will create XSS bug. Another alternative can be that you show what has been searched in the search box only.
