### ISSUE TITLE
Introduzione menù nelle sezioni docs e forum

### ISSUE THREAD

**Issue by sbronzolo** [italia/developers.italia.it#38]
* Problemi*
- Nella sezione forum il menù del sito è incompleto (mancano le voci)
https://forum.developers.italia.it/ 

- Nella sezione docs. il menù del sito è assente
https://docs.developers.italia.it/ 
http://anpr.readthedocs.io/en/sphinx/

- da mobile nelle wl si perde l'accesso al menù del sito

- il sito si chiama developers Italia

in allego ipotesi di architettura dell'informazione e struttura navigazione
@matteodesanti 

*navigazione desktop *
- introdurre nelle wl un menù identico a quello del sito nelle funzionalità, ma di forma ridotta per non appesantire la navigazione della sezione docs. e di quella forum (trattandosi di whitelabel, ereditano la navigazione verticale del prodotto originario)
- nel menù, inserire nome della sezione ben evidente in modo da garantire accesso rapido alla home della wl (viste le sue specificità)

* navigazione mobile*
- si propone di spostare hamburger menu a sinistra in tutto il sito
- limitatamente alle white label, si propone di inserire il nome della wk nel menù
- limitatamente alle white label, mantenere lo spazio a destra per la navigazione contestuale (area personale, search e altre funzioni specifiche della wl)

![studio_menu_sito_e_wl](https://cloud.githubusercontent.com/assets/24827270/24651118/dfcbfbc0-192c-11e7-94c6-a40dbf45af5d.png)

**Comment by alranel** [comment]
Tutte cose sistemate ad oggi, chiudo
