### ISSUE TITLE
Pages for public entities should list software regardless of the iPA code case

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#390]
This page:
https://developers.italia.it/it/pa/pcm
should also list the "IO" software but it doesn't show up because the iPA code has different case. We should filter software in a case-insensitive way.

**Comment by sebbalex** [comment]
@alranel Jekyll array filters don't support case manipulation, it would be a little tricky to show IPA in a case-insensitive way. Could we consider to manipulate ipa case one step above in the chain?

**Comment by libremente** [comment]
This is linked to https://github.com/italia/developers-italia-backend/issues/101

**Comment by libremente** [comment]
Right now all IPA codes are automatically transformed to lowercase, see https://github.com/italia/publiccode-parser-go/commit/b11ec67f97e48f9bd010e6aa53e6e51803e8a127

**Comment by libremente** [comment]
This should be fixed, right @sebbalex? Can I close this?

**Comment by sebbalex** [comment]
Yes, it is @libremente, close it.
