### ISSUE TITLE
Software status filter in search page is broken

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#392]
By selecting more than one option of software status filter in search page, 0 softwares are shown, even if they match the selected criteria. 

An `undefined` is given as searched word.
Pagination footer seems broken as well.

![Screenshot 2019-09-03 at 15 25 44](https://user-images.githubusercontent.com/11008116/64177202-4cf74800-ce5f-11e9-839f-6a83e5ad8cab.png)

**Comment by ffranchina** [comment]
Quick question about the `undefined` part of the issue: which message do you think it would be better to show? Is hiding it completely a viable option?

**Comment by libremente** [comment]
> Quick question about the `undefined` part of the issue: which message do you think it would be better to show? Is hiding it completely a viable option?

@sebbalex ^^

**Comment by ffranchina** [comment]
@sebbalex, any opinion on this?

**Comment by sebbalex** [comment]
I would keep the subtitle message since it represent a sort of "guide" on what to do next. I'd just say something like: "La parola cercata non ha prodotto nessun risultato. Prova un'altra chiave di ricerca."
Thanks

**Comment by ffranchina** [comment]
Great, thanks! Tomorrow morning, I'll submit the PR :)
