### ISSUE TITLE
Creazione di una pagina contatti

### ISSUE THREAD

**Issue by sbronzolo** [italia/developers.italia.it#40]
Content design per creazione di una pagina di contatti
@rasky 

La pagina è organizzata in capitoli e utilizza il menù contestuale come strumento di navigazione

I contenuti sono statici, a parte un widget per twitter e un feed per gli ultimi comunicati stampa

I testi sono già quasi tutti a posto, mancano alcuni indirizzi cui rimandare gli utenti

Va data la possibilità di scaricare foto "ufficiali" e logo, da preparare

https://developers.italia.it/it/contatti/

In allegato il wireframe
![schermata 2017-04-06 alle 16 52 51](https://cloud.githubusercontent.com/assets/24827270/24760647/947a8e70-1ae9-11e7-958f-9cc1d01de851.png)

Zoom 
![Uploading Schermata 2017-04-06 alle 16.54.13.png…]()
![Uploading Schermata 2017-04-06 alle 16.54.02.png…]()

**Comment by rasky** [comment]
OK per me.

**Comment by sbronzolo** [comment]
Aggiungere newsletter

**Comment by alranel** [comment]
Outdated issue, I'm closing
