### ISSUE TITLE
Data produced by crawler should be public

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#406]
Data produced by crawler are stored server side and CircleCI on each commit tries to rsync them to make a fresh and aligned build. When PR comes from external branch CCI doesn't set env vars for security reasons and that rsync will fail. Data are used to create page/card which are public thus we should consider to publish them too. This will allow us to have a more simplified CI pipeline and will simplify local testing too.

@alranel @libremente

**Comment by libremente** [comment]
What do you mean by "publish them"? @sebbalex

**Comment by sebbalex** [comment]
> What do you mean by "publish them"? @sebbalex

we could think to serve them under a static folder in webserver

**Comment by libremente** [comment]
👍

**Comment by libremente** [comment]
Let's serve the public folder via nginx @sebbalex
