### ISSUE TITLE
Check the publiccode ipa with the onboarding ipa

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#410]
I believe the crawler should double check if the ipa declared in a publiccode.yml file is exactly the one expected (the one declared during the onboarding for that specific administration). Of course this is valid exclusively for the PAs, not for third party software.

**Comment by libremente** [comment]
1. This is not the correct repo for this issue
2. Is this still needed?
@sebbalex

**Comment by sebbalex** [comment]
Actually crawler already does this check and lately it is also enforced for `one` command. Closing.
