### ISSUE TITLE
Visual issue when browser window width is in range 991-768 pixels

### ISSUE THREAD

**Issue by luciopileggi** [italia/developers.italia.it#414]
Visual issue when browser window width is in range 991-768 pixels:
![developers italia it-bug](https://user-images.githubusercontent.com/265532/66065117-07ee3080-e547-11e9-982b-1408ec042076.png)

 (OSX Chrome v.77, Safari v.13.01)

**Comment by libremente** [comment]
Thanks @luciopileggi, I am experiencing the same behaviour also on FF 69.

**Comment by masihtak** [comment]
I'm working on it!

**Comment by kerlon5** [comment]
@libremente @masihtak
please, check my PR. sorry if I did something wrong with workflow, my first PR

**Comment by masihtak** [comment]
@kerlon5 This is not an efficient way! actually you didn't solve the issue, you removed it! for beginning I recommend you start with small projects.
