### ISSUE TITLE
Feed RSS is an hidden feature

### ISSUE THREAD

**Issue by ema-pe** [italia/developers.italia.it#419]
Hi, I think that you should provide the ability to follow developers.italia.it news blog using feed RSS. I noticed that you have included ['jekyll-feed' plugin](https://github.com/italia/developers.italia.it/blob/master/_config.yml#L46), it serves a feed XML file on https://developers.italia.it/feed.xml. The problems are:

1. There are not feed RSS icons on https://developers.italia.it/it/news web page;
2. The default feed RSS it only for Italian posts, it is missing for English posts.

The [plugin](https://github.com/jekyll/jekyll-feed) offers some configuration to working on, a solution for the second point is to generate different feed RSS using tags (or 'locale', if it is possible).

**Comment by libremente** [comment]
Thanks @ema-pe for the issue!
You are right, ATM there is not a clear way to access that feed. We can schedule this in a later milestone but, if you would like to work on a proposal and open a PR, we can assist you in doing so.
👍
