### ISSUE TITLE
Graphic issue on search page results

### ISSUE THREAD

**Issue by lucaros97** [italia/developers.italia.it#432]
When searching for something the "no result" UI is not aligned very well and don't look very clear.

Below a screenshot:

![developers italia](https://user-images.githubusercontent.com/8333004/66388787-29c43900-e9c7-11e9-9153-e32cc4b2d7d1.PNG)

And here is my proposed solution:

![developers italia correct](https://user-images.githubusercontent.com/8333004/66388805-347ece00-e9c7-11e9-9c9b-afebb7af33e4.PNG)

**Comment by libremente** [comment]
Hi @lucaros97 and thanks for the contribution. I feel the same. Could you please open a PR so that we can check the code behind the GUI? Thanks a lot!

**Comment by lucaros97** [comment]
Opened PR!
