### ISSUE TITLE
API builder replaces 'it' with 'en' in the slug

### ISSUE THREAD

**Issue by ioggstream** [italia/developers.italia.it#444]
## Reproduce

In the following build:

- https://circleci.com/gh/italia/developers.italia.it/1857?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The generated html page is correctly 

`  ./_site/en/api/dispositivi-corrispettivi.html` 

while the link replace `it` with `en` resulting in the following error `disposENivi`

```
  *  internally linking to /en/api/disposenivi-corrispettivi.html, which does not exist (line 198)
     <a href="/en/api/disposenivi-corrispettivi.html">
```

**Comment by sebbalex** [comment]
Issue were already fixed some time ago, I've updated the `slug` back to original name and rebased the branch in PR https://github.com/italia/developers.italia.it/pull/443 
@ioggstream does it look good?

**Comment by ioggstream** [comment]
@sebbalex see https://github.com/italia/developers.italia.it/pull/443/commits/a02ed3a6be1104a5a539e02b5940c953c98c006c#r381457029

**Comment by sebbalex** [comment]
@ioggstream could we close this?

**Comment by ioggstream** [comment]
I re-ran the workflow, let's see what happens.

**Comment by sebbalex** [comment]
I've rebased the PR and now CI is going good!
