### ISSUE TITLE
Insert vertical scroll for long lists in catalogue

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#463]
Right now the list of supported languages is static and it can get quite long, see https://developers.italia.it/it/software/globaleaks-globaleaks-f22648 for an example. I guess the same structure used in "Categories" in the https://developers.italia.it/it/search page may work. This means using a "See more" button which explodes a div with a vertical scroll. 
Furthermore, this should be true for all the long lists in the catalog.

**Comment by ashu8912** [comment]
working on this ,Hey @libremente can you tell what should be the number of elements to show before adding that show all button

**Comment by libremente** [comment]
Hi @ashu8912, in the case of supported languages the maximum number to show should be 10. 
In the case of the "reuse" key (e.g., https://developers.italia.it/it/software/p_tn-provinciaautonomatrento-pitre) it should be 10 as well.
