### ISSUE TITLE
Readme should be in English as well

### ISSUE THREAD

**Issue by sakshi1499** [italia/developers.italia.it#471]
I think it would be good if the readme of this repository is in English as well. This will help developers who do not understand Italian can understand it easily.

**Comment by libremente** [comment]
Hi @sakshi1499 and thanks for your contribution! You are perfectly right, I have been working on a new version of the README which will be live soon.

**Comment by sakshi1499** [comment]
Oh that is great, I'd love to help if you need some.

**Comment by ridhishjain** [comment]
@libremente, I think we need to have separate instructions for setting up the working environment in windows and Linux.  
````
export ELASTICSEARCH_URL=""
npm install
bundle install
make include-npm-deps
bundle exec jekyll serve
````
in this, `npm install` and `bundle install` works properly but `make include-npm-deps` throws this error in windows

````
developers.italia.it> make include-npm-deps
mkdir -p assets/vendor/
The syntax of the command is incorrect.
make: *** [Makefile:25: include-npm-deps] Error 1
````

**Comment by libremente** [comment]
@ridhishjain I personally did not test the Makefile in a windows environment and I don't have a way to do it. If you want we can try to work together to solve the issue and then we could embed the windows related instructions inside the README file, what do you think?

In this particular case, did you try to use backslashes? 
Something like:
`mkdir -p assets\vendor\`

**Comment by ridhishjain** [comment]
Instead of this, I tried running the same command `make include-npm-deps` on Linux shell Cygwin64 Terminal. It did work!
Then on doing `bundle exec jekyll serve` the machine threw errors regarding eventmachine versions and stuff:

`Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'`
So I added a few configs to solve the problem to Gemfile.lock, nothing changed, just added windows platform!

**Comment by ridhishjain** [comment]
Creating an issue and PR for that

**Comment by libremente** [comment]
Hi @ridhishjain, now leveraging the Docker environment it should be possible to seamlessly take advantage of the system on every docker-compatible system. 
As such, I'm closing this issue for the moment, let me know if you still encounter any issues with it. Thanks! :+1:
