### ISSUE TITLE
Pages have slug with dots are not correctly created and linked

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#473]
Page slug containing dots are not correctly generated, jekyll's plugin tends to interpretate as a subfolder.

Ex:
`slug:uni_ct-UniCt-Easy-Easy-Uni.Co.`

jekyll generates it:
`Writing: .../_site/it/software/uni_ct-unict-easy-easy-uni.co/html.html`

and now as we expect:
`https://developers.italia.it/it/software/uni_ct-unict-easy-easy-uni.co.`

Solutions are two:
- Changing the plugin act [here](https://github.com/italia/developers.italia.it/blob/master/_plugins/data_page_generator.rb#L14) replacing `.` with `_` and as well every link pointing to that page needs to be treated in same way ([here](https://github.com/italia/developers.italia.it/blob/master/assets/scripts/esDevelopersItaliaQuery.js#L928) search results, software related, software page itself, ... ).

- Or we should update plugin as said above and make slug manipulation directly in crawler when writes it in ElasticSearch and data files.

@libremente @alranel thoughts?

**Comment by libremente** [comment]
Let's modify the layer before jekyll (crawler).
