### ISSUE TITLE
Email restricter should be added 

### ISSUE THREAD

**Issue by sakshi1499** [italia/developers.italia.it#474]
While registering any email is allowed to be input, email restriction parameter should be added.

Find a screenshot below where email has been sent to an invalid email id.
![email](https://user-images.githubusercontent.com/42520146/68924027-cd162400-07a5-11ea-97ec-d47eb9ed21b2.PNG)

**Comment by libremente** [comment]
Hi @sakshi1499 and thanks for your contribution. 
Actually [Docs Italia](https://docs.italia.it) is not the target of this repo so for this reason I am closing this issue. Please let me know if you need help in creating an issue on the Docs Italia repository. Thanks! :+1:
