### ISSUE TITLE
Banner in homepage is cut

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#475]
Right now I see the homepage banner in the following way:

![Schermata 2019-11-15 alle 21 54 18](https://user-images.githubusercontent.com/25111463/68975156-c530a100-07f2-11ea-9721-e9dcb82d790d.png)

However, I'd like to see it like this, with a proper padding below:
![Schermata 2019-11-15 alle 21 57 16](https://user-images.githubusercontent.com/25111463/68975345-4d16ab00-07f3-11ea-9923-17625354d443.png)

This behaviour is forced by a `pb-md-0` rule which is forcing the padding bottom to zero. Personally, I don't find this makes a lot of sense. 
@sebbalex @biancini @luciopileggi

**Comment by sebbalex** [comment]
Actual design is in line with mock, check the screen below I've taken from the original prototype:

![Screenshot 2019-11-16 at 11 47 00](https://user-images.githubusercontent.com/11008116/68992105-2abe7500-0867-11ea-8ad4-62ee88bb9307.png)

We still could change it if we think it makes sense.

**Comment by libremente** [comment]
Yeah, I know, however I personally don't like it. I believe having a proper padding makes the message more immediate to see. Furthermore, such padding is removed just in `md`. What do you think?

**Comment by masihtak** [comment]
If you need the changes, I can work on it!

**Comment by libremente** [comment]
I'm closing this since it's not a real issue.
