### ISSUE TITLE
Logos must be rendered in the same way in every view

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#481]
As of now, logos are displayed differently in the `pa` page and the search one. This is suboptimal, we should have (and maintain) a single way of displaying the logos (or screenshots) for every software.

**Comment by ashu8912** [comment]
Hey @libremente  can you share some screenshots of pages where logos differ

**Comment by libremente** [comment]
Sure @ashu8912,
for example see the `SIGLA` case:
1° pic (in `/software` page)
![Schermata 2020-02-01 alle 17 53 24](https://user-images.githubusercontent.com/25111463/73595695-e2385e80-451b-11ea-8ee7-e4465be71106.png)

2° pic (a search result)
![Schermata 2020-02-01 alle 17 53 32](https://user-images.githubusercontent.com/25111463/73595700-ed8b8a00-451b-11ea-81d1-e2b5197f9ebe.png)

**Comment by sebbalex** [comment]
Closed by #561
