### ISSUE TITLE
Main logo not shown

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#486]
The main logo is not shown right now and this is due to a bug in BSI https://github.com/italia/bootstrap-italia/issues/419. The fix has been merged and it should be released in BSI 1.3.9.
This issue is just a reminder so that we know that we have upgrade as soon as the patch will be released. Thanks @francescozaia @sebbalex

**Comment by francescozaia** [comment]
New year's present: https://github.com/italia/bootstrap-italia/releases/tag/v1.3.9 🤞
