### ISSUE TITLE
Visual issues in API pages in mobile view

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#498]
The new API page has some visual flows as shown in the pictures below:
![Screenshot_20200202-140757_Brave](https://user-images.githubusercontent.com/25111463/73609206-ae1c7680-45cb-11ea-8f67-7fcddd85e957.jpg)
![Screenshot_20200202-140640_Brave](https://user-images.githubusercontent.com/25111463/73609207-ae1c7680-45cb-11ea-9dba-a74ee5583e6f.jpg)

**Comment by ridhishjain** [comment]
I'll be working on this issue

**Comment by ridhishjain** [comment]
@libremente, as I am new to the code, can you please tell me how to reproduce the behavior? 😅

**Comment by bfabio** [comment]
@ridhishjain you can reproduce it heading to https://developers.italia.it/it/api/geodati with a mobile device or a small viewport.

**Comment by ridhishjain** [comment]
@bfabio in my localhost:4000, every time I visit `/it/api/...` It throws error:
```
/assets/swagger/swagger.54edb209.css' not found.
/assets/swagger/swagger.dd05dfe5.js' not found.
/assets/swagger/swagger.dd05dfe5.js' not found.
``` 
Not only in `/geodati`, but also in `/muoversi-in-lombardia`, `/daf-ckan` and all others

**Comment by libremente** [comment]
@ridhishjain that's because you need to build also the swagger part, see the Makefile here:
https://github.com/italia/developers.italia.it/blob/ad36177be82405300a615ba0aa5b3589a67446b9/Makefile#L14-L15

My bad, I need to update the README with this info, I will do it in a second

**Comment by ridhishjain** [comment]
@libremente , running is still giving errors:
```
$ ./_buildscripts/build-swagger.sh

> swagger-custom@1.0.0 prebuild F:\gsoc\developers-italia\developers.italia.it\swagger
> npm run prestart


> swagger-custom@1.0.0 prestart F:\gsoc\developers-italia\developers.italia.it\swagger
> if [ ! -d node_modules ]; then npm install; fi

! was unexpected at this time.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-custom@1.0.0 prestart: `if [ ! -d node_modules ]; then npm install; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-custom@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ridhish\AppData\Roaming\npm-cache\_logs\2020-02-06T06_09_48_931Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-custom@1.0.0 prebuild: `npm run prestart`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-custom@1.0.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ridhish\AppData\Roaming\npm-cache\_logs\2020-02-06T06_09_49_042Z-debug.log
```
