### ISSUE TITLE
Windows configurations does not exist in Gemfile

### ISSUE THREAD

**Issue by ridhishjain** [italia/developers.italia.it#499]
For setting up the development environment in windows, the configs currently present in Gemfile.lock are not sufficient 
especially for `eventmachine`
Additions for windows required
I am working on this!

**Comment by libremente** [comment]
Hi @ridhishjain and thanks for your issue. 
Usually I like to be quite conservative when dealing with dependencies, especially when new ones have to be added just to tackle corner cases. 
I need to investigate a little bit more on this particular one before actually merging your PR. 
Could you please provide some links to the resources you used to add this dependency?
We will let you know, thanks for the efforts!

**Comment by ridhishjain** [comment]
As the `eventmachine` was throwing error:
`Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'`
`eventmachine` is provided as x64-mingw platform gem but somehow do not supports ruby2.4 or 2.5 right..
https://github.com/eventmachine/eventmachine/issues/820
This issue I found on eventmachine dealt with the same problem. A simple solution was to uninstall the already existing gem and install it again by forcing `--platform ruby`

Once this is done, we do not need to do it everytime the bundle installs as resolved in https://github.com/eventmachine/eventmachine/pull/833, therefore updating existing dependencies can deal with the problem

So, after doing `gem install eventmachine --platform ruby`, same thing is done for `ffi`, `nokogiri`, `rest-client`....and finally added `x64-mingw32` to the platform list

**Comment by ridhishjain** [comment]
@libremente, u looking for this?

**Comment by bfabio** [comment]
This should actually be an eventmachine bug and it's fixed by eventmachine/eventmachine#833.

Feel free to reopen this if it's not the case!
