### ISSUE TITLE
No results found header shown also where results are found

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#506]
![Schermata 2020-02-11 alle 17 09 24](https://user-images.githubusercontent.com/25111463/74255161-c25e2300-4cf1-11ea-9dca-900fcdd9612d.png)

Steps to reproduce:
1. search for a term that has some results;
2. The results page shows the results expected;
3. in the results page, select one or more filters on the left that produce a combination with no real results: an error header is inserted;
4. now un-select those filters: the page shows the results as in 1) however the error header is not removed.

Seems like the page is not correctly "refreshed" or the error header is not correctly toggled when switching from no-results to yes-results.

**Comment by sebbalex** [comment]
Sort by filter and results number are disappeared from view, this is mostly due to previous bugfix.
