### ISSUE TITLE
Errore Redirect Logo

### ISSUE THREAD

**Issue by pgoodjohn** [italia/developers.italia.it#52]
Cercando di ritornare alla home dalla pagina [Errori Anpr](https://italia.github.io/anpr/error/error_errori_anpr.html.html), cliccando sul logo _.it_ si viene rediretti ad una pagina di [errore 404](https://italia.github.io/anpr/error/) anziché alla homepage effettiva.

Steps per riprodurre:
- Recarsi sulla pagina [ANPR](https://developers.italia.it/it/anpr/)
- Cliccare su [tabella codici ed errori](https://italia.github.io/anpr/)
- Nella pagina aprire il menú 'errori' e selezionare una delle due opzioni
- Cliccare sul logo
- Errore 404

**Comment by mccalv** [comment]
Ciao, attualmente stiamo usando https://anpr.readthedocs.io. Ho corretto la documentazione e creato una pull request. 
Grazie per la segnalazione!
