### ISSUE TITLE
Get rid of deprecation warning by bundler at build time

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#532]
At build time bundler shows those warning message:

> [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/'`, and stop using this flag

> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.

**Comment by zaza81** [comment]
I can get this issue. 
The **first warning** should be an easy fix by defining the path in the configuration instead of as a parameter in the install command. 

The **second warning** can be eliminated by setting gem tzinfo-data for all systems instead for only the win systems

**Comment by libremente** [comment]
Hi @zaza81 and thanks for your interest!
Yes, I think you are right, the first one is straightforward whilst the second one needs a bit of testing to ensure that such a change is non-destructive. Did you manage to setup the docker environment flawlessly?
We'll be happy to review your PR :rocket:

**Comment by zaza81** [comment]
@libremente the Docker container runs fine 👍 
I've just made a PR, thanks!

**Comment by libremente** [comment]
This can be close, thanks again @zaza81.
