### ISSUE TITLE
[en] Sezione news  

### ISSUE THREAD

**Issue by gvarisco** [italia/developers.italia.it#54]
La versione inglese del sito (https://developers.italia.it/en/) non contiene ad oggi una sezione 'news' (ref. https://developers.italia.it/news/).

- [ ] Creazione https://developers.italia.it/en/news/
- [ ] Traduzione e allineamento news IT con l'equivalente inglese (ad oggi, 13/04, c'è un solo comunicato da tradurre: https://github.com/italia/developers.italia.it/blob/master/_posts/it/2017-02-24-lancio.md

**Comment by mriccia** [comment]
Ciao @gvarisco, ho fatto una traduzione iniziale, nei prossimi giorni la rifinisco e apro una PR.
https://github.com/mriccia/developers.italia.it/commit/9e15d13a2064f13985fe56ca43c252cceae9c26c

**Comment by gvarisco** [comment]
@mriccia ciao Michele, ottimo! Appena la mandi inizio a rivederla :)

**Comment by mriccia** [comment]
Ho creato una PR che contiene solamente il post in Inglese, sto cercando di creare la sezione news in EN ma non so se l'approccio é corretto. 
Ho spostato la `news.html` nella cartella `_layouts` e ho creato due `news.md` files, uno per IT ed uno per EN. Cosa ne pensi?  https://github.com/italia/developers.italia.it/compare/master...mriccia:en-news?expand=1

**Comment by alranel** [comment]
Issue risolta nei giorni scorsi in #321 by @sebbalex e @libremente
