### ISSUE TITLE
Add contributors list in README file

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#569]
We should have a clear list of contributors in the README file. 
I think this one could be nice: https://github.com/all-contributors/all-contributors/blob/master/README.md

Any thoughts @sebbalex?

**Comment by libremente** [comment]
https://allcontributors.org/

**Comment by sebbalex** [comment]
I like the idea but I would love to have something more "in line" with our style, sort of our [Contact page](https://developers.italia.it/it/contatti/).
What do you think?

**Comment by libremente** [comment]
Ok, let's create a link to that page from the README file. Closing, thanks!
