### ISSUE TITLE
Remove Hacktoberfest from to-do page

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#571]
Since the program is not active anymore I think it would be nice to remove its reference from the https://developers.italia.it/it/cosa-fare/ page. 
At least we could hide the entry from the menu on the right so that if we'll use it in the future it will be easy to switch it back again.

**Comment by alexghirelli** [comment]
Ciao @libremente, se me la assegni posso farla io velocemente questa

**Comment by libremente** [comment]
Perfetto @alexghirelli! Facci sapere se ti serve una mano :+1:

**Comment by alexghirelli** [comment]
Ciao @libremente se non è un problema, potresti scrivermi su Slack? Mi fallisce la build del container

**Comment by libremente** [comment]
Ciao @alexghirelli, hai avuto modo di provare il token? Grazie!

**Comment by libremente** [comment]
Siccome siamo ormai arrivati alla nuova versione di Hacktoberfest direi che questa issue si può chiudere perchè il tag serve di nuovo e la riapriremo quando sarà finito l'evento. Grazie!
