### ISSUE TITLE
Reuse software - Logo not correctly formatted

### ISSUE THREAD

**Issue by vlauciani** [italia/developers.italia.it#576]
Hi all

The logo shown in the Developers Italia Software page (https://developers.italia.it/it/software/), is not correctly formatted; the text is cutted. 

Please, check the attached image.

Thank you.

![Screenshot 2020-05-21 at 16 15 28](https://user-images.githubusercontent.com/16477095/82568066-8d7a2b80-9b7e-11ea-9a07-1acfc74aeb98.png)

**Comment by sebbalex** [comment]
Hi @vlauciani we were already aware of this issue and as of now @libremente is working on a fix that will unify all views and fix render problems with logos.
See here: https://github.com/italia/developers.italia.it/pull/561
