### ISSUE TITLE
Link ad api-oas-checker in API page

### ISSUE THREAD

**Issue by ioggstream** [italia/developers.italia.it#586]
## I expect

To link/present api projects in developers.italia.it/it/api

- [ ] https://teamdigitale.github.io/api-oas-checker/ online validator in API page 
- [ ] https://github.com/teamdigitale/api-starter-kit
- [ ] https://teamdigitale.github.io/openapi/

## Instead

There's none

## Notes

Editorial Ideas welcome

**Comment by sebbalex** [comment]
cc @libremente

**Comment by bfabio** [comment]
Those are now linked in the new pages https://next.developers.italia.it/it/interoperabilita/ and https://developers.italia.it/it/pdnd/.
