### ISSUE TITLE
.well-known/security.txt results in 404

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#592]
**Describe the bug**
After #147 we have a `.well-known` dir which serves `security.txt` files.
Switching to GH pages this file is not served anymore and GET https://developers.italia.it/.well-known/security.txt
resulting in 404.

**To Reproduce**
`curl https://developers.italia.it/.well-known/security.txt`

**Expected behavior**
File security served.

**Comment by libremente** [comment]
I believe this is fixed, please @LucaPrete confirm thx.

**Comment by LucaPrete** [comment]
Sì, il file è ora visibile. Chiudo.
