### ISSUE TITLE
Metriche per dashboard

### ISSUE THREAD

**Issue by rasky** [italia/developers.italia.it#60]
Con l'obiettivo di arrivare ad una dashboard di monitoraggio della community, iniziamo a scrivere un tool che raccolga alcune informazioni a livello numerico e le invii ad un'istanza di [statsd](https://github.com/etsy/statsd):

GitHub:
 * Numero progetti attivi
 * Interazioni su GitHub (issue / PR)

Discourse:
 * Numero post sul forum
 * Iscritti al forum

Mailup:
 * Iscritti alla newsletter

**Comment by biancini** [comment]
Implemented dashboards on the Team pages, here:

- Slack: http://bit.ly/dboard-slack
- Forum: http://bit.ly/dboard-forum
- Github: http://bit.ly/dboard-github
