### ISSUE TITLE
ANPR Dashboard API  wrong Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by zaza81** [italia/developers.italia.it#608]
**Describe the bug**
when trying to use GET /comune/{codice_istat} in swagger frontend, I get the following message:

TypeError: Origin https://developers.italia.it is not allowed by Access-Control-Allow-Origin.

--

**To Reproduce**
1. Go to https://developers.italia.it/it/api/anpr-dashboard
2. Click on /comune/{codice_istat}
3. Click on Try it out
4. Click on Execute
5. Scroll down to Server Response
4. See error  TypeError: Origin https://developers.italia.it is not allowed by Access-Control-Allow-Origin.
--

**Expected behavior**
I was expecting the migration status regarding comune 016024 (default input value)

**Comment by libremente** [comment]
Thanks @zaza81 for this issue!
We're working on it and we'll let you know as soon as we'll have updates.

**Comment by sebbalex** [comment]
Hello @zaza81 

CORS parameter for these calls have been tuned and now the toolbox is fully functional.

![Screenshot 2020-07-31 at 15 45 59](https://user-images.githubusercontent.com/11008116/89041051-ffbc7880-d344-11ea-8649-bb116df3a51e.png)

Thanks!

**Comment by zaza81** [comment]
Thanks for fixing @sebbalex, it works like a charm!
