### ISSUE TITLE
Clicking on the software thumbnails always brings up the first image

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#610]
**Describe the bug**

Despite what thumbnail you click on, the first image is always maximized

**To Reproduce**

**Expected behavior**
The clicked image should be maximized instead

**Screenshots**

![Peek 10-08-2020 14-14](https://user-images.githubusercontent.com/788293/89781560-e15c3700-db13-11ea-85ad-97195b594642.gif)

**Comment by libremente** [comment]
This will be handled by the new component structure of the website, wont-fix for now
