### ISSUE TITLE
Display supported languages of software in a user friendly way

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#613]
Language should be listed as the user would expect, instead of ISO codes or weird technical names ("Greek, Modern (1453-)" should be just "Greek")

Additionally, they should be translated to whatever language the user is navigating the site in.

As reference, the current supported languages for https://developers.italia.it/it/software/globaleaks-globaleaks-f22648
![Schermata da 2020-08-11 16-28-28](https://user-images.githubusercontent.com/788293/89909865-d1b22080-dbef-11ea-947e-96bc14612854.png)

**Comment by libremente** [comment]
This is sort of related to https://github.com/italia/developers-italia-backend/issues/162. Let's dig deeper into it and see if we can find a proper way to solve it
