### ISSUE TITLE
Search should explicitly state it when it doesn't find results

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#616]
When you search for something that doesn't yield any result, the site doesn't make it explicit and there's a visual glitch with the blue button.

We should at least print something along the lines of "No results found" . It would be nice to display an empty state image as well.

![Peek 12-08-2020 08-45](https://user-images.githubusercontent.com/788293/89983890-c1925380-dc78-11ea-8942-8809e9830cb6.gif)

**Comment by sebbalex** [comment]
This is fixed by #654 but still there is a little glitch with icons used in modal search where the first and last ones are svg from BSI and others are directly imported as assets. Since these icons are important assets for every PA we should look forward to insert them into BSI directly.

**Comment by sebbalex** [comment]
I'm close this and eventually track details above in a new dedicated issue.

**Comment by bfabio** [comment]
> Since these icons are important assets for every PA we should look forward to insert them into BSI directly.
> 
> wdyt @libremente @bfabio

100% agree
