### ISSUE TITLE
assets shouldn't be a volume in Docker

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#619]
`assets` is mounted as a volume in https://github.com/italia/developers.italia.it/blob/master/docker-compose.yml#L21, but it should not because it contains stuff that the developer might want to modify (images or local scripts).

**Comment by sebbalex** [comment]
@bfabio I'd probably remove also `_data`, for same reason. FAQ, translations, links are stuff that the developer might want to modify as well.
I would keep just statics assets as volume mount, and maybe `_data/crawler` which is used to download fresh crawled data and keep clean the repository staging area. What do you think?

**Comment by bfabio** [comment]
@sebbalex Agreed! I was considering it when I wrote the issue, but I ruled it out because I mistakenly thought it contained only downloaded data.

+1 on `_data/crawler` as a volume.
