### ISSUE TITLE
Search results page shows empty Hai cercato""

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#634]
**Describe the bug**

The search results page does not show the string used for running the query.

**To Reproduce**
1. Use the search bar
2. Enter a string
3. Results page shows `Hai cercato""`

**Expected behavior**

The keyword string should be present or that results' page string should be changed.

**Screenshots**

![Schermata da 2020-08-14 10-20-14](https://user-images.githubusercontent.com/25111463/90229604-79aa3280-de18-11ea-85c9-a986805a4379.png)

**Comment by bfabio** [comment]
Depends on #646.
