### ISSUE TITLE
Do we really want the first screenshot to be the preferred thumbnail?

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#641]
The current order of preference for software thumbnails is:

1. First screenshot
2. Logo
3. Placeholder

Do we really want the first screenshot to be the preferred one? Screenshots are usually indiscernible at small sizes and not very appealing in general.

Popular stores use the logo:

* https://flathub.org/home
* https://play.google.com/store/apps
* https://snapcraft.io/store

**Comment by libremente** [comment]
For reference: https://github.com/italia/developers.italia.it/blob/8c01df6590ec99cf64bf2b6af1e6218b14d5c594/_includes/display-logo.html#L23
