### ISSUE TITLE
Pagina "Cosa fare"

### ISSUE THREAD

**Issue by rasky** [italia/developers.italia.it#65]
Aggiungiamo una pagina "Cosa fare" che elenchi un subset di tutte le issue aperte in tutti i repositori GitHub di Developers Italia.

In particolare, la pagina deve mostrare del testo iniziale di introduzione, e poi una tabella che contenga dei "record" composti da:

 * Titolo della issue (con link verso Github)
 * Eventuali label della issue 
 * Titolo del sotto-progetto (cioè del progetto GitHub, es: `Plugin Wordpress di SPID`). NOTA: questo non è il nome git del repositorio GitHub, è il titolo descrittivo associato che si può inserire dentro github.
 * Titolo del progetto di riferimento (es: `SPID`). Questo può essere dedotto dal prefisso del nome del repo su GitHub (es: `spid-wordpress` -> `SPID`).

Inoltre, deve essere possibile filtrare per:

 * Progetto (es: SPID).
 * Sottoprogetto (non è prioritario).
 * Tecnologia (sottoinsieme delle label su GitHub che indica la tecnologia di riferimento, es: tech-php).
 * Difficoltà (sottoinsieme delle label su GitHub che dà una stima di massima della complessità del task, es: diff-easy).
 * Tipologia (sottoinsieme delle label, es: "feature" o "bug")

**Comment by matteodesanti** [comment]
Ecco il mockup: potrebbe essere qualcosa del genere
https://invis.io/KFAOM2OUE#/251168809_1024up_-_Todo
Non ho previsto la funzione "applica filtri", poichè https://datatables.net/ li applica live.
Per le select multiple userei un altro grande classico, https://github.com/select2/select2
