### ISSUE TITLE
Review the prefix of the repos listed in the todo page

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#663]
As of now, these are the prefixes of the repo names checked for the [todo](https://developers.italia.it/it/cosa-fare/) page: https://github.com/italia/developers.italia.it/blob/86b0060381c8bcac5f9b01166217239930226ef2/_config.yml#L34

Seeing #662 I believe we should review such a list and make it consistent with the help needed. 
For example, we should remove the `daf-` ones.

**Comment by libremente** [comment]
@ioggstream I believe this is of interest also for you

**Comment by bfabio** [comment]
@libremente That key is kinda misleading: those are just the prefixes we can turn to a human readable project in the UI (ie. "lg-" becomes "Linee guida" or "Guidelines").

We always get all the projects in the organization.

**Comment by libremente** [comment]
Please leave a comment in the _config.yml file @bfabio

**Comment by ioggstream** [comment]
`api-` is missing.

**Comment by bfabio** [comment]
@libremente Turns out we already did it when refactoring `github_importer.rb` https://github.com/italia/developers.italia.it/blob/master/scripts/github_importer.rb#L13-L15 :)
