### ISSUE TITLE
Search engine must have all available types in filter

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#680]
**Describe the solution you'd like**

As of now in search page we have only three different Type as filter (Platforms, OSS, Reuse SW) but I expect to have all available types that live in catalog, such as: Administrations, API.

**Describe alternatives you've considered**

**Additional context**

**Comment by emilioSp** [comment]
I think that with the refactoring of the search engine we can close this.

The search page will show only the software available in the catalogue.
The Administrations and API have their own page and they are however searchable through the search modal.
