### ISSUE TITLE
API are filtered in search modal but not in search page

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#682]
**Describe the bug**

API are searched by search modal but not in search page. If you type a valid API in modal suggestions appears in box below as it should but searching all over site doesn't show same results.

**To Reproduce**

![Screen-Recording-2020-09-11-at-1](https://user-images.githubusercontent.com/11008116/92896588-ca637a00-f41c-11ea-8a58-e1d34b28d012.gif)

**Comment by emilioSp** [comment]
As for [this](https://github.com/italia/developers.italia.it/issues/680), I think that this issue could be closed with the release of the new search engine. The api won't show in the catalogue page, but they remain searchable in the search modal.

**Comment by sebbalex** [comment]
> As for [this](https://github.com/italia/developers.italia.it/issues/680), I think that this issue could be closed with the release of the new search engine. The api won't show in the catalogue page, but they remain searchable in the search modal.

Closing.
