### ISSUE TITLE
"Intro","How to become a S.." section box is fixed, as a result it scroll up from the view port when scrolling

### ISSUE THREAD

**Issue by kmlhsn** [italia/developers.italia.it#687]
**Describe the bug**

"Intro","How to become a S.." section box under "platfrom -><items detail>" is fixed, as a result it scroll up from the view port when scrolling
**To Reproduce**

1. Go to 'https://developers.italia.it/''
2. Click on 'Platforms'
3. Click on 'Read more' from any items. I clicked "SPID"
4. Click on "Documentation, SDK, Graphic resources, Tools" on the right side box

**Expected behavior**

Right side item box should be always in view-port of the page.
**Screenshots**

![image](https://user-images.githubusercontent.com/32615215/92997219-6d0e1c80-f533-11ea-965f-015361d740ab.png)

![Untitled-1](https://user-images.githubusercontent.com/32615215/92997226-86af6400-f533-11ea-8795-7bab68845db7.gif)

**Smartphone (please complete the following information):**
Lenovo Thinkpad
Windows 10
Mozilla Firefox
80

**Additional context**
Add any other context about the problem here.-->

**Comment by ameybhavsar24** [comment]
I think this is more appropriate as a 'feature request`.

If we're making this, here's a demo by adding `position:sticky; top:100px` to `.sideblock`.

![projectsticky](https://user-images.githubusercontent.com/28699912/99671990-d4e36500-2a98-11eb-9f9f-a6cbf95805ff.gif)

cc/ @libremente @bfabio

**Comment by bfabio** [comment]
@ameybhavsar24 that's not bad :thinking: 

@libremente @sebbalex wdyt?

**Comment by sebbalex** [comment]
> @ameybhavsar24 that's not bad 
> 
> @libremente @sebbalex wdyt?

I like it!

**Comment by sebbalex** [comment]
@ameybhavsar24 could you please submit a PR?

**Comment by ameybhavsar24** [comment]
> @ameybhavsar24 could you please submit a PR?

Sure.
