### ISSUE TITLE
"Community leaders" Does not have "Dot" Pagination. 

### ISSUE THREAD

**Issue by kmlhsn** [italia/developers.italia.it#688]
**Describe the bug**

"Community leaders" Only have one "Dot" for pagination. 
**To Reproduce**

1.Go to 'https://developers.italia.it/''
2.Click on 'Platforms'
3.Click on 'Read more' from any items. I clicked "SPID"

**Expected behavior**

"Community leaders" should have two "Dot" for pagination. 
**Screenshots**

![image](https://user-images.githubusercontent.com/32615215/93000939-2a593e00-f54d-11ea-881d-3ff8f25fb669.png)

**Smartphone (please complete the following information):**
Lenovo Thinkpad
Windows 10
Mozilla Firefox
80

**Additional context**
Add any other context about the problem here.-->

**Comment by bfabio** [comment]
@kmlhsn Thanks for the issue, confirming. This can be a good Hacktoberfest issue!

**Comment by UchihaCFC** [comment]
@bfabio Can I do this? I see that it is not assigned yet and it would be a good start :)
