### ISSUE TITLE
Build the Docker image as part of the CI pipeline and use it

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#691]
**Is your feature request related to a problem? Please describe.**
Sometimes we aren't able to catch certain errors earlier in the pipeline, fe:
* Anything related to Dockerfile and its build
* Version mismatch of software (fe. ruby version)
* Mismatch in the steps of the build among the environments (Dockerfile, CircleCI and Netlify) 

**Describe the solution you'd like**
Have the Docker image build as the first step of the pipeline and use it as the environment to build the site with a single command.
One nice side effect is the Docker image can be automatically tagged and pushed to DockerHub.

There's a very preliminary patch for this at https://github.com/bfabio/developers.italia.it/tree/circleci

**Comment by libremente** [comment]
In Vercel this is not possible.

**Comment by bfabio** [comment]
At this point we should just simplify the build, see https://github.com/italia/developers.italia.it/issues/1007
