### ISSUE TITLE
Use the resized image in avatars from GitHub

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#692]
Whenever we are displaying a GitHub user (eg. https://developers.italia.it/en/contacts, https://developers.italia.it/en/18app/ and other Platforms), we are using the full size image, only to resize it with HTML.

We should just get the resized image from GitHub, with the appropriate `s=` parameter:
* `https://avatars2.githubusercontent.com/u/788293?v=4`
vs
* `https://avatars2.githubusercontent.com/u/788293?v=4&s=48`

This would benefit clients with low speed connections.

**Comment by adrienluitot** [comment]
Hello,
I think I can work on it, if it's okay for you? :D

**Comment by bfabio** [comment]
@adrienluitot Go for it :)

Those files are downloaded during build, here they are:

[github.zip](https://github.com/italia/developers.italia.it/files/5282471/github.zip)

**Comment by adrienluitot** [comment]
Thanks :D

**Comment by adrienluitot** [comment]
Hello,

I started working on it, but the community leaders, maintainers... don't seem to appear on the pages.
Do I need a github access token ?

**Comment by bfabio** [comment]
Hello @adrienluitot, make sure those yaml files are in the `_data` directory.

How are you building the site?

**Comment by adrienluitot** [comment]
Yep I added the files.

I launch it like this : `sudo docker-compose up` should I add the `--build` argument ?

**Comment by bfabio** [comment]
Are you on [our Slack](https://slack.developers.italia.it/)? We can sort this out on the `#website` channel.

**Comment by adrienluitot** [comment]
Hello, I'm on it ;)
