### ISSUE TITLE
Images supposed to be in background make the layout resize

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#699]
Images that should be just background decoration make the content change position when the image finishes loading.

Example, contact page: https://developers.italia.it/en/contacts
![Peek 16-09-2020 15-20](https://user-images.githubusercontent.com/788293/93343023-4cdea600-f830-11ea-9fea-a6c09ce3b7d0.gif)

The content should not change position while the image loads.

**Comment by Laischon** [comment]
Hi! At the moment the image is not loaded as background, nor with a position absolute.

Below I am attaching two alternatives that in addition to setting the image in the background also avoid the scrolling of the elements.
![devit_3](https://user-images.githubusercontent.com/7593569/93670429-9da60700-fa9b-11ea-8d2a-9c6f93349316.PNG)
![devit_2](https://user-images.githubusercontent.com/7593569/93670431-9ed73400-fa9b-11ea-9662-895d7d3a8772.PNG)

Let me know which one you prefer.

Nicholas

**Comment by bfabio** [comment]
Hey @Laischon, the second one looks better to me. @sebbalex, @libremente wdyt?

Note that we have the same issue on other pages as well (eg. https://developers.italia.it/en/how, https://developers.italia.it/en/get-involved, https://developers.italia.it/en/news/, etc.)

**Comment by libremente** [comment]
Yes, the second one looks better to me as well.
I believe we should work on all the images in a dedicated PR, WDYT?

**Comment by Laischon** [comment]
Ok! Done.
Let me know what you think about. 😅
