### ISSUE TITLE
The search modal should autofocus the input field

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#718]
The search field is not focused by default when the search modal is opened, requiring the user to click on it.
Tested on Firefox and Chromium.

![Peek 28-09-2020 13-38](https://user-images.githubusercontent.com/788293/94427854-0a9e5880-0190-11eb-8be6-7403d9147384.gif)

**Comment by qwerty-rgb** [comment]
I would like to work on this issue.
Suggest some ways to get started.

**Comment by bfabio** [comment]
Hello @qwerty-rgb!

You can start bringing up the development environment as described in https://github.com/italia/developers.italia.it#development and start investigating `_includes/search-modal.html`.

Happy coding!

**Comment by qwerty-rgb** [comment]
<div id="searchModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="container">
          <p class="h1 modal-title d-inline"> {{ t.search_form_label | capitalize }}</p>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="container">
          <form autocomplete="off" action="">
            <div class="form-group">
              <div class="autocomplete">
                <svg class="icon icon-lg">
                  <use xlink:href="/assets/svg/sprite.svg#it-search"></use>
                </svg>
                <input autofocus type="text" class="form-control" placeholder="{{ t.search_form_label | capitalize }} {{ t.software.platforms }}, software{% if active_lang == 'it' %} o amministrazioni{% else %} or administrations{% endif %}">
                <div id="suggestions" class="d-none"></div>
              </div>
              <div id="search-buttons">
                <a class="btn py-2 px-4 mb-2 btn-filter all active" data="all"><svg class="icon"><use xlink:href="/assets/svg/sprite.svg#it-search"></use></svg>{% if active_lang == 'it' %} Tutto {% else %} All {% endif %}</a>
                <a class="btn py-2 px-4 mb-2 btn-filter platforms" data="platforms"><span class="icon icon-type-platform--gray"></span>{{ t.software.platforms | capitalize }}</a>
                <a class="btn py-2 px-4 mb-2 btn-filter software_open" data="software_open"><span class="icon icon-type-generic-sw--gray"></span>{{ t.software.software_open | capitalize }}</a>
                <a class="btn py-2 px-4 mb-2 btn-filter reuse_software" data="reuse_software"><span class="icon icon-type-public-sw--gray"></span>{{ t.software.reuse_software | capitalize }}</a>
                <a class="btn py-2 px-4 mb-2 btn-filter administrations" data="administrations"><svg class="icon"><use xlink:href="/assets/svg/sprite.svg#it-pa"></use></svg>{{ t.software.administrations | capitalize }}</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

//just added autofocus in the input field

**Comment by qwerty-rgb** [comment]
is the above way of submitting code is the right way

**Comment by sebbalex** [comment]
> is the above way of submitting code is the right way

Thanks for your effort, but I'm here to ask you more :) could you please open a PR with your solution?

**Comment by qwerty-rgb** [comment]
i am new here can u please guide me how to do it

**Comment by qwerty-rgb** [comment]
how can i push the changes

**Comment by amycruz97** [comment]
can i take on this

**Comment by libremente** [comment]
Hi @qwerty-rgb, did you figure out how to open a PR for this?
Hi @amycruz97, are you planning to open a PR for this issue?

**Comment by amycruz97** [comment]
yes for hackoberfest

**Comment by amycruz97** [comment]
i have cloned the repo.what do i do next. where can i find where to make changes

**Comment by amycruz97** [comment]
Hello, the where can i find the file  to make changes on

**Comment by libremente** [comment]
@amycruz97 please read carefully the whole discussion, hints are already present. Thank you
