### ISSUE TITLE
Software name lenght exceeds column width

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#719]
**Describe the bug**
![Schermata da 2020-09-28 18-43-26](https://user-images.githubusercontent.com/25111463/94461747-d4c29980-01ba-11eb-8fb6-efcc99474800.png)

As you can see from the screenshot, the name is too long and overlaps other elements on its right. This is probably due to the fact that the dots make it impossible to naturally split it with a return.

## Reproduce
Look for that software in the search results page

**Comment by Samkit-shah** [comment]
where is this page? how to reproduce this bug?

**Comment by libremente** [comment]
Hi @Samkit-shah, you can search for `rer flask` for example and hit enter. 
This is the results page:
![Schermata da 2020-09-29 10-06-42](https://user-images.githubusercontent.com/25111463/94530562-8c978b80-023b-11eb-986c-1f03cc3f1644.png)
The issue appears in the first results on the left.
