### ISSUE TITLE
Button background color makes it difficult to read the text

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#722]
![Schermata da 2020-09-30 09-47-17](https://user-images.githubusercontent.com/25111463/94657727-2c1f5180-0302-11eb-8f37-a069037253aa.png)

When hovering the button in /it/software page the background goes blue and it's hard to read the blue text in it. 
We should probably stick with the white color.

**Comment by UshasriMavuri1999** [comment]
Hey @libremente , Can you please assign this issue to me? I would like to work on this:)

**Comment by libremente** [comment]
Hi @UshasriMavuri1999 that would be great! Waiting for you PR then :+1:

**Comment by varunpusarla** [comment]
I'd like to contribute in case the issue is still open.

**Comment by bfabio** [comment]
Hi @UshasriMavuri1999, are you still working on the PR?

**Comment by varunpusarla** [comment]
Sorry, I wasn't able to do it. You can unassign me.

**Comment by maurovitale** [comment]
Hi, I solved this issue but in the meantime, it's been done a PR by another user. Should I still do the PR of what I did ?
