### ISSUE TITLE
Icon wrapper rendered without the twitter icon in news

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#723]
**Describe the bug**

There is a blue dot representing the icon wrapper (see image at the bottom) next to the author name in every news. This links to twitter but the icon is missing. 

![Schermata da 2020-09-30 10-53-25](https://user-images.githubusercontent.com/25111463/94664640-6b9e6b80-030b-11eb-9c3c-dea064b39f77.png)

See https://developers.italia.it/it/news/2019/11/14/terminato-hacktoberfest-tiriamo-le-somme for example

We should use an SVG icon as for the other icons.

**Comment by ameybhavsar24** [comment]
I have got a fix and making a PR soon.

**Comment by libremente** [comment]
Great @ameybhavsar24 , assigning it to you, thanks!
