### ISSUE TITLE
Hover text on links to Twitter in news pages

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#725]
In the news pages, the link to Twitter should describe itself more clearly, hinting it's a link to share the current news on Twitter, for example displaying "Share on twitter" on mouse hover or next to the icon.

![Peek 30-09-2020 12-55](https://user-images.githubusercontent.com/788293/94676802-32bac280-031c-11eb-88ef-42405c9ba6dd.gif)

**Comment by 1880akshay** [comment]
Can I work on this issue? Please assign it to me.

**Comment by ameybhavsar24** [comment]
Do you think the `title="Share on Twitter"` attribute should suffice?
Something like:
![RipeUnhappyFirecrest-size_restricted](https://user-images.githubusercontent.com/28699912/94679419-ade0a080-033d-11eb-99d9-0d4afd1a7fb1.gif)

**Comment by bfabio** [comment]
@ameybhavsar24 That would do it :+1: I'm assigning this to @1880akshay as they asked first, if you don't mind. Feel free to review the resulting PR!

**Comment by ameybhavsar24** [comment]
Not a problem. Don't know why @1880akshay deleted his comment.

**Comment by bfabio** [comment]
@ameybhavsar24 Nevermind, @1880akshay deleted the comment. You can go ahead if you want :smiley:

**Comment by 1880akshay** [comment]
@bfabio sorry for the inconvenience, actually I am not much familiar with the tech stack used in this project due to which I was facing issues while running the code locally, so that is why I deleted my comment.

**Comment by bfabio** [comment]
@1880akshay Don't worry, thanks for the clarification :+1:
