### ISSUE TITLE
Platforms thumbnails should have a friendly name and possibly a short description

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#726]
The Platform thumbnails (fe. at https://developers.italia.it/it/piattaforme) should include the full project name as well (fe. Anagrafe Nazionale Popolazione Residente (ANPR), Carta d'Identità Elettronica (CIE)) as prescribed by the AAAAA (American Association Against Acronyms Abuse).

A short description below the title would also be a welcome improvement.

![image](https://user-images.githubusercontent.com/788293/94679097-d35eb180-031f-11eb-83f8-e1a40a6c5ee2.png)

**Comment by shamikakumar** [comment]
Can I work on this issue ?

**Comment by libremente** [comment]
Hi @shamikakumar, thanks for your interest. Are you proficient in Italian to work on this issue?

**Comment by shamikakumar** [comment]
No.. let me check out other issues I can work on, thanks!
