### ISSUE TITLE
Close news category icon not shown 

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#730]
**Describe the bug**
When browsing the news it is possible to select one of the categories.
![Schermata da 2020-10-01 15-21-12](https://user-images.githubusercontent.com/25111463/94814554-cadaa980-03f9-11eb-85ee-27090ec07e60.png)

When selecting for example "Community" it should also be possible to deselect it. 
As you can see below, the "close" icon is not present and there is a weird blue box around the "community" text.
![Schermata da 2020-10-01 14-42-23](https://user-images.githubusercontent.com/25111463/94814436-9cf56500-03f9-11eb-973a-2f1f4af447f3.png)

Please use SVG icons in order to be consistent with the rest of the project, thanks.

**Comment by ccatterina** [comment]
Hi, I would like to work on this. Can you assign this issue to me? Thanks

**Comment by libremente** [comment]
Hi @ccatterina, sure thing! Thanks for your time!
