### ISSUE TITLE
Software text overlap

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#733]
**Describe the bug**
As seen below, there is an overlapping of the "Leggi di più" text over the software description.
![WhatsApp Image 2020-10-02 at 09 52 50(2)](https://user-images.githubusercontent.com/25111463/94903447-1e9ccf80-049a-11eb-8671-55e088b1dd31.jpeg)

**To Reproduce**
1. Go to the software page with a mobile browser

**Comment by ayushkumarsinha** [comment]
I'd like to work on this issue

**Comment by libremente** [comment]
HI @ayushkumarsinha, how are you planning to solve this issue? Thanks!

**Comment by twopill** [comment]
@libremente 
Ciao ho fixato il problema, ma provando a modificare il **main.css** ma non appaiono modifiche da poter pushare.

**Comment by gabrielatricak** [comment]
Can I be assigned to this issue?

**Comment by Guiguerreiro39** [comment]
Hello,
I can't seem to reproduce this issue.. Is it fixed already?

**Comment by bfabio** [comment]
@Guiguerreiro39 It's not, you can reproduce it by navigating to https://developers.italia.it/en/search and shrinking the viewport to something mobile-sized.

**Comment by bfabio** [comment]
Fixed by #778.
