### ISSUE TITLE
Wrong margins in categories cloud

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#734]
**Describe the bug**

News categories cloud does not have proper margins when browsed via mobile, see image below:
![WhatsApp Image 2020-10-02 at 09 52 50(1)](https://user-images.githubusercontent.com/25111463/94903798-9c60db00-049a-11eb-9b5e-5e7aa945e07c.jpeg)

**Comment by itsnitinr** [comment]
Hi, could I work on this, please?

**Comment by ayushkumarsinha** [comment]
I'd like to work on this issue

**Comment by bfabio** [comment]
@itsnitinr Sure, go ahead :+1:

**Comment by itsnitinr** [comment]
Hi @libremente. I've been trying to setup docker-compose on my Majaro Linux environment for an hour now but it doesn't seem to work. Possibly a kernel issue. Please assign the issue to someone else as I may not be able to get it running. Sorry.

**Comment by aritropc** [comment]
I'd like to work on this issue!
Can you please provide the URL to the page where the glitch?

**Comment by aritropc** [comment]
![image](https://user-images.githubusercontent.com/32550413/94949283-4c1b6480-04fe-11eb-9749-0a2b23e9d6ec.png)
Does it look cool?

**Comment by bfabio** [comment]
@aritropc It looks good :+1:

**Comment by bfabio** [comment]
@aritropc Looking forward to your PR :slightly_smiling_face:

**Comment by aritropc** [comment]
Actually, I'm facing problems with Docker :(
I know the fix... I'll commit the changes as soon as I'm done!
Sorry for the delay @bfabio

**Comment by yeppog** [comment]
@bfabio Hi I've sent in a PR that fixes the margins #786
