### ISSUE TITLE
No margin in footer entry 

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#735]
**Describe the bug**

Footer entry "Follow us on" does not have proper margins.
See image below:
![WhatsApp Image 2020-10-02 at 09 52 50](https://user-images.githubusercontent.com/25111463/94903922-d0d49700-049a-11eb-9674-3b8dfe996759.jpeg)

**Comment by Joshuafolorunsho** [comment]
could you expatiate more ? 

![image](https://user-images.githubusercontent.com/55793353/94907450-1a6fb280-0498-11eb-8723-3588d0ebfb49.png)

**Comment by libremente** [comment]
> could you expatiate more ?
> 
> ![image](https://user-images.githubusercontent.com/55793353/94907450-1a6fb280-0498-11eb-8723-3588d0ebfb49.png)

Hi @Joshuafolorunsho, I like your proposal! What do you think @bfabio?

**Comment by urmauur** [comment]
can you @libremente assign it to me?

**Comment by bfabio** [comment]
@libremente Looks good :+1:

**Comment by libremente** [comment]
Thanks @Joshuafolorunsho, waiting for your PR :wink:

**Comment by varunpusarla** [comment]
In case it's still open, I'd like to work.

**Comment by bfabio** [comment]
@Joshuafolorunsho are you sill working on a PR for this one?

@varunpusarla In case they're not, you can go ahead and work on it.

**Comment by Guiguerreiro39** [comment]
Hello,
It seems they're not working on this.. Can i take it?

**Comment by bfabio** [comment]
@Guiguerreiro39 Sure, thanks for your interest :+1:
