### ISSUE TITLE
Counter-intuitive arrow icons in header

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#736]
**Describe the bug**

When browsing the website via mobile browser, there are a set of arrows at the top right corner of the header that are very counter-intuitive and hard to use. 
We should review their layout. 

![new_image](https://user-images.githubusercontent.com/25111463/94905572-63763580-049d-11eb-9921-8c249da55e14.jpeg)

Similarly, we should just write just the acronym -something like `MID` or `DTD`- when the mobile layout is triggered instead of the complete "Dipartimento.." form.

**Comment by akashprasher** [comment]
What if I reduce the size of the text to 0.8rem?
![image](https://user-images.githubusercontent.com/42891970/94909829-6420c300-04c1-11eb-88b5-ab87d4ce1a8e.png)

**Comment by libremente** [comment]
> What if I reduce the size of the text to 0.8rem?
> 
> ![image](https://user-images.githubusercontent.com/42891970/94909829-6420c300-04c1-11eb-88b5-ab87d4ce1a8e.png)
> 
> If yes, please assign this task to me.

Thanks @akashprasher for your interest. WDYT @bfabio? I believe it could work

**Comment by bfabio** [comment]
@libremente :+1:

**Comment by libremente** [comment]
Waiting for you PR then @akashprasher! Thanks!! :rocket:
