### ISSUE TITLE
Ugly vertical spacing in website name

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#737]
**Describe the bug**

`Developers Italia` has too much vertical spacing and no margin from the logo. This is very ugly IMHO. We should find a way to fix it. 
![WhatsApp Image 2020-10-02 at 10 46 43(1)](https://user-images.githubusercontent.com/25111463/94905987-06c74a80-049e-11eb-9aa6-463e8ab99679.jpeg)

**Comment by Joshuafolorunsho** [comment]
I can work on this. can you assign me @libremente ?
Also this is on mobile, right?

**Comment by libremente** [comment]
Hi @Joshuafolorunsho, thanks for your interest. Yes, this is related to mobile. If you browse developers.italia.it you should see this happening.

**Comment by twopill** [comment]
Ciao @libremente , ho provato a fixare .
Spero sia tutto ok perché questa è la mia prima pull request lol.

Questo è il link al fix: [https://github.com/italia/developers.italia.it/pull/745](https://github.com/italia/developers.italia.it/pull/745)

**Comment by bfabio** [comment]
Hello @twopill, this issue was already assigned to @Joshuafolorunsho. Maybe you can work together?

**Comment by bfabio** [comment]
Hi @Joshuafolorunsho, are you still working on it?

**Comment by maurovitale** [comment]
Hi @bfabio, I have the solution for this problem if @Joshuafolorunsho is not working on it anymore, I also aligned the search icon 

![header_space](https://user-images.githubusercontent.com/4927957/97078586-67edc400-15ed-11eb-9e32-e037f786a3ab.png)

**Comment by bfabio** [comment]
@maurovitale Great, I assigned this to you :+1:
