### ISSUE TITLE
Use a single image as placeholder image for reuse software

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#743]
We should use just one image as placeholder for reuse software instead of `cover_softwareriuso.png` and `placeholder-software-riuso.jpg` and call it `software_riuso.png`.

_Originally posted by @libremente in https://github.com/italia/developers.italia.it/pull/742#discussion_r498870749_

**Comment by libremente** [comment]
Uhm @bfabio sorry my bad I didn't explain well. My point was just to simply rename the `softwareriuso` file into `software_riuso` :smile: I believe it can be nice to show two different placeholders, WDYT?

**Comment by eliteReaper** [comment]
Can I be assigned to this? @bfabio

**Comment by UchihaCFC** [comment]
@bfabio 

Do you want to always use the same image regardless of the category where you are? Right now cover\_softwareriuso.png is used if the category is equal to 'public-sw' if the cover\_software\_opensource.png is not applied, would it be to replace this logic by always using a single one called 'software\_riuso.png'? or simple rename the cover\_softwareriuso.png image to software\_riuso.png?

**Comment by bfabio** [comment]
@libremente Sorry, I actually added another piece to what you mentioned because I noticed [`cover_softwareriuso.png`](https://github.com/italia/developers.italia.it/blob/master/assets/images/cover_softwareriuso.png) and [`placeholder-software-riuso.png`](https://github.com/italia/developers.italia.it/blob/master/assets/images/placeholder-software-riuso.jpg) are basically the same image.

Note I was not talking about `cover_software_opensource.png`.

**Comment by UchihaCFC** [comment]
@bfabio Ok, I understand that you just have to rename the image to a new name, I would like to be able to contribute, not only with this issue, could we start with this one? if not tell me if there's another frontend I can contribute to;) Thanks!

**Comment by libremente** [comment]
> @libremente Sorry, I actually added another piece to what you mentioned because I noticed [`cover_softwareriuso.png`](https://github.com/italia/developers.italia.it/blob/master/assets/images/cover_softwareriuso.png) and [`placeholder-software-riuso.png`](https://github.com/italia/developers.italia.it/blob/master/assets/images/placeholder-software-riuso.jpg) are basically the same image.
> 
> Note I was not talking about `cover_software_opensource.png`.

Ok, makes sense, just please take into consideration the size (in px) of those images. If we get rid of one (which is the best way IMHO) we should consider resizing it as needed.

**Comment by bfabio** [comment]
> I'm wondering if there is a need of having two different extensions JPG and PNG though..

I think it just happened with no real reason. We should use PNG.

**Comment by bfabio** [comment]
@eliteReaper Of course, there you go! :+1:

**Comment by bfabio** [comment]
@UchihaCFC I assigned @eliteReaper as they asked first, but we have more in this very repo. :wink: 

https://github.com/italia/developers.italia.it/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest

Here you can find issue for other repos in our organization: https://developers.italia.it/en/to-do
It would be nice to merge your contribution!

**Comment by UchihaCFC** [comment]
@bfabio Thank you! I'm going to take a look at the other issues to see if I can help with any of them ;)

**Comment by eliteReaper** [comment]
> 
> 
> > @libremente Sorry, I actually added another piece to what you mentioned because I noticed [`cover_softwareriuso.png`](https://github.com/italia/developers.italia.it/blob/master/assets/images/cover_softwareriuso.png) and [`placeholder-software-riuso.png`](https://github.com/italia/developers.italia.it/blob/master/assets/images/placeholder-software-riuso.jpg) are basically the same image.
> > Note I was not talking about `cover_software_opensource.png`.
> 
> Ok, makes sense, just please take into consideration the size (in px) of those images. If we get rid of one (which is the best way IMHO) we should consider resizing it as needed.
> 
> I'm wondering if there is a need of having two different extensions JPG and PNG though..

Looking at the code in place for ['placeholder-software-riuso.jpg'](365x175 px), I observe that depending on the value of ['codiceIPA'] either the former or ['cover_software_opensource.jpg'](544x352 px) is selected as the placeholder image.

I believe by simply renaming [`cover_softwareriuso.png`](544x352 px) to ['software_riuso.png'] and changing the required lines for both this and ['placeholder-software-riuso.jpg'] we can achieve the desired result.

Please correct me if I am mistaken.

**Comment by bfabio** [comment]
@eliteReaper That's correct.

**Comment by bfabio** [comment]
This should also fix the white borders we have in thumbnails:

![Schermata da 2020-11-18 09-46-02](https://user-images.githubusercontent.com/788293/99513061-847de180-298a-11eb-989f-c16ecd00e6a5.png)

**Comment by SAP-20** [comment]
Could you assign the project to me??

**Comment by UchihaCFC** [comment]
@SAP-20 It is assigned to @eliteReaper right? I wanted to do it but he was already with it

**Comment by bfabio** [comment]
@UchihaCFC you're right, but we also started [a refactoring](https://github.com/italia/developers.italia.it/compare/feat/refactoring) which will turn those thumbnails into a component.

My advice is to wait for it.

**Comment by UchihaCFC** [comment]
Great, maybe after refactoring this is no longer necessary. We will wait, in case @eliteReaper want to continue or if either of us can do it. Thank you @bfabio!

**Comment by bfabio** [comment]
@UchihaCFC @eliteReaper refactoring was merged :rocket:

**Comment by UchihaCFC** [comment]
@eliteReaper will you continue to work with it? 

@bfabio if he doesn't want to continue, I wish I could help with this starting from the merge 🙂

**Comment by bfabio** [comment]
@UchihaCFC thanks :)

Anyway, maybe this was fixed by the refactoring itself, is this the case @emilioSp?

**Comment by emilioSp** [comment]
First of all, thank you @UchihaCFC 

The refactoring has solved the issue. Now we use only `cover_softwariuso.png` [here](https://github.com/italia/developers.italia.it/blob/a524900b5a018adddf05d17d0250b387fed121c4/assets/js/services/searchEngine.js#L94). Btw in the codebase there still is `placeholder-software-riuso.jpg` and I think we should get rid of it and use `cover_softwareriuso.png` everywhere (or another name if you prefer).

With a rapid search, I have found the duplicated jpg [here](https://github.com/italia/developers.italia.it/blob/ec0d9f4015fc1634bec8dc8c7e1a0113cc460c46/_includes/display-logo.html#L18).

wdyt @bfabio ?

**Comment by bfabio** [comment]
@emilioSp agreed. It would also be nice to use the new component (`CatalogueItem.js) wherever we are using display-logo.html now.

**Comment by emilioSp** [comment]
@bfabio 
Yes, however, we should take into account that the `CatalogueItem` component is rendered by React on document load.

I don't know where the _display-logo.html_ is used but we should take SEO problems into account.
Another little concern is the interaction with Jekyll. Many props in _display-logo.html_ come from others `_includes` and are generated at build time. Perhaps we could render them into custom element attributes and then pass them into the React component at runtime. (I think that was your initial idea)

On the other hand, we will gain the advantages of having a single component, with a single style everywhere!

If we are confident with the SEO, we could proceed as you suggest

**Comment by bfabio** [comment]
@emilioSp Uhm, I didn't think about SEO, good point :thinking: . Doesn't Google bot support Javascript these days?

**Comment by emilioSp** [comment]
Mmm I'm not sure, but [server-side rendering](https://reactjs.org/docs/react-dom-server.html#reference) and frameworks like Gatsby are born to meet even SEO purposes.

**Comment by bfabio** [comment]
We discussed internally and we realized that we have a sitemap, so SEO should not be a concern.

@UchihaCFC I'm going to open a new issue about using the new `CatalogueItem` component everywhere, of course feel free to ping me or @emilioSp in case you need help or guidance :)

**Comment by bfabio** [comment]
Turned into #915
