### ISSUE TITLE
https://developers.italia.it/en/faq is empty

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#753]
https://developers.italia.it/en/faq has no content. We should provide a translation of https://developers.italia.it/it/faq

**Comment by libremente** [comment]
Yes, we need someone to translate the ITA FAQs into ENG.

**Comment by lmillucci** [comment]
Isn't this a duplicate of #600 ?

**Comment by bfabio** [comment]
Oops, you're right @lmillucci, thanks.
