### ISSUE TITLE
De-hardcode the language from rtd links

### ISSUE THREAD

**Issue by ruphy** [italia/developers.italia.it#76]
Review all links to the documentation so that they are not language-specific.

For example, this page https://developers.italia.it/it/spid/ links to https://spid-regole-tecniche.readthedocs.io/en/latest/
which is wrong because:
1. the documentation is in Italian, not English
2. we miss on the possibility of having translations

We need to do a global review of all the links, there might be other similar situations

**Comment by bvhme** [comment]
I've just bumped in to trying to find the English docs for DAF and when switching the language of the page in the DAF readme getting redirected to the home page.

Did find them at https://daf-docs.readthedocs.io/en/latest/

**Comment by alranel** [comment]
This fix was applied to all the links in the website. Documentation is now hosted on docs.italia.it, where the multi-language switch links are being fixed in these days.
