### ISSUE TITLE
"More tags" button in the homepage has wrong style

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#760]
The "More tags" button at https://developers.italia.it/en has different style than the rest of the buttons:

![image](https://user-images.githubusercontent.com/788293/95493206-735db000-099c-11eb-92e8-af1a74e86298.png)

it should be blue and with more padding.

**Comment by riyabhatia26** [comment]
Can I work on this please?

**Comment by BhargaviChada** [comment]
I want to work on this issue ,and I am new to git  so can you please tell me which html file do I have to work with? I can't actually find the index.html file
