### ISSUE TITLE
Switch logo

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#764]
We need to switch to the new logo of the DPT

**Comment by bfabio** [comment]
@libremente 

![image](https://user-images.githubusercontent.com/788293/95577716-fdf0ee80-0a32-11eb-9acb-0b42cd7524f6.png)
# Or
![image](https://user-images.githubusercontent.com/788293/95577787-1e20ad80-0a33-11eb-9ea3-eb99dd809a14.png)

**Comment by sebbalex** [comment]
first one :smile:
