### ISSUE TITLE
The viewport moves horizontally on mobile devices

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#768]
**To Reproduce**

1. Go to https://developers.italia.it on a mobile device
2. Scroll left
3. The viewport moves

![untitled](https://user-images.githubusercontent.com/788293/95652050-a1530980-0aee-11eb-8e1f-4c85a9bf097b.gif)

**Comment by ranabirbasu12** [comment]
Can I work on this?

**Comment by Yash7818** [comment]
may i work on this
@bfabio

**Comment by ameybhavsar24** [comment]
@bfabio The overflow is caused due to negative margin at `.home-listing-items .row`. It should be active only for 576px and up.

https://github.com/italia/developers.italia.it/blob/f8e6f15102bb285d7d47f60eaaa7663a80721aa2/assets/scss/main.scss#L904-L907

I am making a PR to fix it.
