### ISSUE TITLE
Add meta tags for social media

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#776]
Right now, when a developers.italia.it link is shared on social media (TW, IN, FB), the site's logo does not appear. This should be fixed using the proper meta tags.

**Comment by PrasannaBH** [comment]
Where?

**Comment by masihtak** [comment]
I will doing this!

**Comment by sebbalex** [comment]
For some pages such as news would be nice to have a dedicated tag in jekyll where ad inline image could be set as a cover image for such sharing in social networks. wdyt? @libremente

**Comment by bfabio** [comment]
News pages have an SVG image in the meta tag, and [Twitter doesn't support that](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup):

`<meta property="twitter:image" content="https://developers.italia.it/assets/icons/logo-it.svg" />`

But I agree with @sebbalex. It would be nice to be able to use different images to make the tweet more interesting.

**Comment by libremente** [comment]
Yes, good idea!
