### ISSUE TITLE
Homepage boxes too narrow at certain resolutions

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#783]
**Describe the bug**
Boxes at the bottom of the homepage are too narrow at certain resolutions

**To Reproduce**
1. Go to https://developers.italia.it/en
2. Scroll down to the "Forum", "Slack", "GitHub", "Docs" boxes
3. Shrink the viewport until you see the error

![Peek 16-10-2020 09-11](https://user-images.githubusercontent.com/788293/96224307-a3eeac80-0f8f-11eb-8422-888e54f80d21.gif)

**Comment by baranwal** [comment]
I have sent you my PR regarding the same.
