### ISSUE TITLE
Short platform descriptions in homepage

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#792]
The platforms boxes in the homepage should have a short description like they have in https://developers.italia.it/en/platforms.

![image](https://user-images.githubusercontent.com/788293/96691591-5bffc900-1385-11eb-97d1-8dfe98ba48fc.png)

**Comment by RabsonJ** [comment]
Assign this issue to me please

**Comment by bfabio** [comment]
@RabsonJ thanks for your interest :rocket:

**Comment by ameybhavsar24** [comment]
Hi @bfabio. This issue has been open for long. Can I take this?
Passing
```
itemdescription='subtitle'
```
to 
https://github.com/italia/developers.italia.it/blob/0ba0f4cc06589009991f81fc0f2eb7e2cd2aee03/_layouts/home.html#L60-L68
should probably solve this.

**Comment by bfabio** [comment]
Sure, thanks @ameybhavsar24 :heart:
