### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by sbronzolo** [italia/developers.italia.it#81]
@jovi vedevo su search console che developers italia è l’unico tra i nostri siti senza site map https://support.google.com/webmasters/answer/156184

**Comment by gvarisco** [comment]
@sbronzolo è stata creata recentemente, con l'upgrade a jekyll. Puoi farne il submit? https://developers.italia.it/sitemap.xml

**Comment by gvarisco** [comment]
Fatto io.

**Comment by sbronzolo** [comment]
Ok

Inviato da iPhone
