### ISSUE TITLE
duplicazione contenuti / title e description

### ISSUE THREAD

**Issue by sbronzolo** [italia/developers.italia.it#82]
Vedo che esiste duplicazione delle description in due casi

a) pagina inglese del contenuto, ma il contenuto è in italiano e duplica quello della pagina italiana
https://developers.italia.it/en/privacy-policy/

b) pagine tag come questa, hanno title e description fisse
https://developers.italia.it/news/eventi
La soluzione ottimale dovrebbe essere
Title = eventi
Description = Tutte le news relative a eventi

**Comment by alranel** [comment]
La privacy policy è in attesa di traduzione. La seconda issue ad oggi non è più presente
