### ISSUE TITLE
Wrong content in https://developers.italia.it/it/cosa-fare

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#826]
https://developers.italia.it/it/cosa-fare says

> In questa pagina, raccogliamo tutte le issue aperte di tutti i progetti

but that's not true because that page shows just the issues with the `help wanted` label.

We should also make clear to maintainers how to get issues listed on that page. cc @dej611

**Comment by libremente** [comment]
https://github.com/italia/developers.italia.it/blob/5724aeaed98c6b4c69a714f7965a47d864fa5c3e/en/to-do.md the ENG version has the right copy
