### ISSUE TITLE
Software pagination can be improved

### ISSUE THREAD

**Issue by francescozaia** [italia/developers.italia.it#833]
**Describe the bug**
Hi Developers! 😬 
When browsing the [software page](https://developers.italia.it/it/search?type=reuse_software&page=0&sort=relevance) the pagination is not working as expected.

**To Reproduce**
1 - I'm on the software page,
2- When page number is changed (say, I'm on page 2),
3- I click on a software,
4- I click "back" on the browser,
5- I land back on page 0.

This is quite annoying when looking for different software options.

**Expected behavior**

- add the page change event as proper browsing history in order to move back to the correct page even when I exit from the listing
- open any software in a new tab - this is something many commercial player already do, not sure if that's ok for us

**Comment by libremente** [comment]
Thanks @francescozaia, confirming this weird behaviour.

**Comment by emilioSp** [comment]
We will close this issue using the infinite scroll, included in the next release of the search engine.

**Comment by sebbalex** [comment]
@emilioSp does the search listing page have an anchor link as a reference in which point of the research you were? This can be useful in situation supposed by @francescozaia

**Comment by emilioSp** [comment]
Nope. The searching starting from the start. I remove the _fixed in dev_ label.

If we want to simplify the code, as @francescozaia advised, we can open the software page in a new tab. 

Is it a feasible solution? @sebbalex @libremente
