### ISSUE TITLE
Use the CatalogueItem everywhere in the site for software items

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#915]
As discussed in #743, it would be nice to use `CatalogueItem` everywhere and replace the logic in `display-logo.html` with it.

We should make Jekyll generate a custom element <catalogue-item> in place of what we do now, and use its attributes to pass down the data (like description, name, logo, etc.) to CatalogueItem's React props.

cc @emilioSp @UchihaCFC

**Comment by emilioSp** [comment]
This is the React.js [entrypoint](https://github.com/italia/developers.italia.it/blob/master/assets/js/App.js).

We should do something similar we already did with `custom-search` and `custom-catalogue`.

The `CatalogueItem` expected input is [here](https://github.com/italia/developers.italia.it/blob/master/assets/js/utils/proptypes.js).

**Comment by UchihaCFC** [comment]
Ok I see @bfabio, I'm going to try to do it, (is there a deadline for this? Maybe it will take a bit 😅 to check everything well)

Thanks for the info @emilioSp I'll take a good look at it.

**Comment by bfabio** [comment]
@UchihaCFC Don't worry, there's no deadline, feel free to take your time :)
