### ISSUE TITLE
Team members are only visible by organisation members

### ISSUE THREAD

**Issue by giux78** [italia/developers.italia.it#94]
Team members are only visible by organisation members following the links:

https://developers.italia.it/it/daf/#i-project-leader-di-questo-progetto

https://github.com/orgs/italia/teams/daf  

You are asked to login.

**Comment by alexrj** [comment]
Hm, the team is already set to "visible", but that does not make it truly public. It looks like there's no way to display team members publicly. I think the best solution is to add people profiles manually to `_data/people.yml` and display thumbnails automatically in the project pages, like we already do for teamdigitale.governo.it.
cc @ruphy

**Comment by alexrj** [comment]
Alternative idea: get team members from API at website build time. We'd still need to map GitHub nicknames in the website config files.
https://developer.github.com/v3/orgs/teams/#list-team-members

**Comment by alexrj** [comment]
Fixed by #99
