### ISSUE TITLE
Stato avanzamento CIE

### ISSUE THREAD

**Issue by fiorins** [italia/developers.italia.it#953]
# Issue content
Buongiorno, dal sito di innovazione.gov.it sono stati tolti i grafici che mostravano gli avanzamenti e i progressi della CIE nei vari comuni ?

**Comment by bfabio** [comment]
@fiorins grazie della segnalazione, puoi aprirla nel repository del sito: https://github.com/teamdigitale/innovazione.gov.it-site/issues?

Nel frattempo qui c'è il link diretto della dashboard:
https://dashboards.innovazione.gov.it/public/dashboard/2cad5098-aa8a-453d-a3da-6a239ccef62c

**Comment by fiorins** [comment]
Ok, aperta

**Comment by bfabio** [comment]
Aperta come https://github.com/teamdigitale/innovazione.gov.it-site/issues/46
