### ISSUE TITLE
Don't stretch images in API catalogue

### ISSUE THREAD

**Issue by mfortini** [italia/developers.italia.it#961]
**Describe the bug**
Images in the API catalogue are stretched

**To Reproduce**
See here (https://github.com/teamdigitale/api-openapi-samples/commit/4e575a6e88824724f6a4b00b12ce3a2569ed5a1f)

https://developers-italia-it-73lyxmjam-dip-trasformazione-digitale.vercel.app/it/api

![image](https://user-images.githubusercontent.com/1104926/115701713-5b61e280-a368-11eb-83ea-482267a9d88b.png)

**Expected behavior**

The original logo is here https://telematici.agenziaentrate.gov.it/resources/img/AgenziaEntrate_logo_152.png
![image](https://user-images.githubusercontent.com/1104926/115701842-82201900-a368-11eb-9e0a-72f61cc48bcc.png)

**Comment by sebbalex** [comment]
I'd probably remove the `w-100` class on logos using thus original ratio, this should look like:
![Screenshot from 2021-04-26 11-47-19](https://user-images.githubusercontent.com/11008116/116063553-62009a80-a685-11eb-8061-c8cd9b32d134.png)

wdyt @mfortini @ioggstream ?

**Comment by ioggstream** [comment]
@sebbalex I prefer the previous layout with fixed height. Is that a problem?

**Comment by mfortini** [comment]
LGTM both in chrome and firefox, please go ahead

**Comment by sebbalex** [comment]
@ioggstream @mfortini I made a commit up on existing PR #773 please have a look at it.
Preview [here](https://developers-italia-it-45n8u7oz5-dip-trasformazione-digitale.vercel.app/it/api)

**Comment by ioggstream** [comment]
love it. Go!!!

**Comment by ioggstream** [comment]
@sebbalex rock!
