### ISSUE TITLE
Dates in news pages are only English localised

### ISSUE THREAD

**Issue by sebbalex** [italia/developers.italia.it#985]
**Describe the bug**

Dates for news pages are only in English even if another language is set.

**To Reproduce**

1. Go to news page
2. Dates are only in English even if Italian is selected
3. Click on a news
4. Also here, dates only in English

**Expected behavior**

I Expect to see them localised as per selected language.

**Comment by bfabio** [comment]
Looks like Jekyll just ignored the issue and all the solutions are either gone or archived.

We need implement it manually with a local plugin, which is kind of ewww...
